### PR TITLE
[bug fix] could not find WgsMetrics

### PR DESCRIPTION
**Pull request by nh13**
See above

### CODE REVIEW

**Comment by nh13** [comment]
Build failure doesn't look related to my changes (in setup).  @ewels can you take a look?

**Comment by ewels** [comment]
Yes, apologies - new dependencies coming out with new requirements broke the Python 2.7 tests. I've removed support for Py2k now and the tests are passing again.

**Comment by ewels** [comment]
Many thanks for this @nh13!

**Comment by alexandre-nadin** [comment]
Could you please update the bioconda package to integrate this patch? Latest version has been the 1.8 since <3months ago. Many thanks!

**Comment by ewels** [comment]
Hi @alexandre-nadin 

I am working towards a v1.9 release currently. It should be done pretty soon now, then I will push a new bioconda release.

As a general point, anyone can do new patch releases on bioconda, it doesn't have to be me. So if this is very important to you then you are welcome to do so (others have in the past).

Phil

**Comment by alexandre-nadin** [comment]
Thank you very much @ewels . Originally I found and fixed the issue in the package code from bioconda, then I decided to make a pull request. I checked and saw this patch before doing the fork.

It is not urgent but for curiosity I will check how to make a release in bioconda as I have never done it. 

Alex

**Pull request merged**
