### PR TITLE
New module: Bustools (inspect)

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
- [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` has been updated

 - [x] There is example tool output for tools in the https://github.com/ewels/MultiQC_TestData repository or attached to this PR
 - [x] Code is tested and works locally (including with `--lint` flag)
 - [x] `docs/README.md` is updated with link to below
 - [x] `docs/modulename.md` is created
 - [x] Everything that can be represented with a plot instead of a table is a plot
 - [x] Report sections have a description and help text (with `self.add_section`)
 - [x] There aren't any huge tables with > 6 columns (explain reasoning if so)
 - [x] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
 - [x] Module does not do any significant computational work

Added bustools (inspect) module. Bustools generates a convenient single-cell format. It can also generate QC statistics, and this should now be supported by MultiQC.

**I added a lot of stuff to the general statistics table, is it too much?**

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
I'll make sure all boxes can be ticked today

**Comment by apeltzer** [comment]
Ah, perfect for the scrnaseq pipeline 😄

**Comment by ewels** [comment]
Many thanks for this @Maarten-vd-Sande - finally got around to taking a quick look at this. I fixed the merge conflicts and pulled in upstream changes, then got the tests to pass.

> I added a lot of stuff to the general statistics table, is it too much?

Yeah it is a bit on the large side. Might be worth making this into a bustools-specific table and then pulling out just one or two columns to put into General Stats - what do you think?

**Comment by Maarten-vd-Sande** [comment]
@ewels thanks for picking this up, I kinda forgot about it :see_no_evil: 

I will change it into a separate table.

**Comment by Maarten-vd-Sande** [comment]
@apeltzer @FloWuenne and @KevinMenden seeing as you guys are excited about this PR, any preference for what information stays at the general table, and what I will move to the bustools section? Any requests for plots? Otherwise I will keep the barplots as is, move everything to a table in the bustools section, and keep `Bus records`, `mean reads per barcode`, `distinct UMIs`, `2x depth`, and `% whitelisted barcodes`

see:
http://ocimum.science.ru.nl/bustools.html

**Comment by apeltzer** [comment]
That sounds reasonable to me :-)

**Comment by KevinMenden** [comment]
Yes that sounds good :-) thanks!

**Comment by Maarten-vd-Sande** [comment]
@ewels this is now ready for review. Thanks a lot for fixing the merge conflicts before :pray:

**Comment by ewels** [comment]
@Maarten-vd-Sande - looking good, thanks! I've just pushed a couple of commits to your PR where I fiddled with a few things, please take a look and check that you agree with everything I've done. In brief:

* Tried to use lambdas to make the numbers more manageable in the tables (see [docs](https://multiqc.info/docs/#number-base-multiplier))
* Added some `shared_key` attributes so that the background bars share a scale in the tables
* Made the General Stats table even more lean by hiding some columns by default
* Removed some config keys which were set to default values (eg. `"hidden": False`).
* Moved some section text from `description` into `helptext`
* Other minor text changes

**Comment by Maarten-vd-Sande** [comment]
@ewels looks good!

**Review by ewels — APPROVED** [review]

**Comment by ewels** [comment]
Thanks for this @Maarten-vd-Sande!

**Comment by Maarten-vd-Sande** [comment]
@ewels thanks for multiqc!

**Pull request merged**
