### PR TITLE
edit code in FastQC module to allow MultiQC reporting 'Per Tile Sequence Quality'

### PR DESCRIPTION
**Pull request by mticlla**
Many thanks to contributing to MultiQC!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things I request on pull requests (PRs).

## If this PR is _not_ a new module
 - [ ] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` has been updated
 - [x] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change

### CODE REVIEW

**Comment by ewels** [comment]
Hi @mticlla, thanks for this! Could you explain a little what this is for?

Phil

**Comment by mticlla** [comment]
Hi Phil,

Yes I can explain. FastQC reports include a ['Per tile sequence quality plot'](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/12%20Per%20Tile%20Sequence%20Quality.html), which is currently not included in the MultiQC report. Creating the same plot for multiple fastqc files is quite tricky and I'm not sure how to plot it so that it can be informative. However, it is still informative to include a section in the MultiQC report indicating how many fastq files failed/succeeded  the 'Per tile sequence quality' check. This pull request is just about the later.

Please see the attached image for an example on how the updated MultiQC report would look!
image

Monica

**Comment by ewels** [comment]
Ok cool - thanks! I'm not super keen on having a whole section for a plot that will never be there, essentially just to show the status.

Instead, an idea that has been floating around for a little while is to have a table showing all FastQC statuses for each sample. That could be in its own section. What do you think about this instead?

Phil

**Comment by ewels** [comment]
Hi @mticlla,

I've just added a new section to the FastQC module that shows a heatmap with all statuses:

image

Hopefully this solves your use case - let me know if you have any thoughts!

I'll close this PR now. Many thanks for your work though.

Phil

**Comment by mticlla** [comment]
Thanks a lot Phil, I think this is a good solution. Sorry for my lack in
response before, had to switch to another project and completely forgot to
come back to you with a reply.

Monica

**Comment by ewels** [comment]
Great, glad to hear it - thanks! 👍

**Pull request closed without merging**
