### PR TITLE
Add Picard VariantCallingMetrics report parsing

### PR DESCRIPTION
**Pull request by cpavanrun**
Hej @ewels ,

Herewith an extension for Picard to also parse VariantCallingMetrics reports.

- [x] This comment contains a description of changes (with reason)
- [X] `CHANGELOG.md` has been updated
- [X] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change. PR for test data is here: https://github.com/ewels/MultiQC_TestData/pull/105

An example report, based on the test data can be found ~here~ (no longer works because of IT migrations).

Cheers,
Chris

### CODE REVIEW

**Comment by cpavanrun** [comment]
I am still a bit new to PyCharm and the IDE suddenly decided to add Python 3 hints to a default class. Should be fixed and `--force` pushed rebase.

**Comment by cpavanrun** [comment]
@ewels: I thought this was already pulled.

**Comment by cpavanrun** [comment]
No prob. Phil. Why are you reading github when you are on holiday? ^^ 
I took the liberty of fixing the merge conflict (simple CHANGELOG clash).

Cheers.

**Comment by cpavanrun** [comment]
Post-holiday bump. =D

**Comment by ewels** [comment]
Sorry @cpavanrun! Post holidays I had lots of travelling for work and now I have lots of emails 😞 Will hopefully have a MultiQC morning in a week or so and then this is a top priority 🔝

**Comment by ewels** [comment]
Hi Chris,

Apologies again for the very long time it's taken me to get to this. PR looks great - just taken the code for a spin and it works flawlessly. Many thanks!

Phil

**Pull request merged**
