### PR TITLE
Illumina Dragen module

### PR DESCRIPTION
**Pull request by vladsaveliev**
Following the request at https://github.com/ewels/MultiQC/issues/1055, started a module that supports QC files from a tumor/normal variant calling pipeline (targeted or whole genome). Reporting on:
- mapping metrics (similar to `samtools stats`)
- coverage stats (similar to `mosdepth` and `qualimap bamqc`)
- variant calling QC
- run time metrics
- fragment size metrics 
- and ploidy estimation.

Perhaps doesn't fit in perfectly as a typical MultiQC module because Dragen is more like a Swiss army knife that does tons of jobs from demultiplexing to SV calling, instead of focusing more or less on one certain task, so it's hard to even classify it as "pre-processing", "aligner" or "post-alignment". However we will be using Dragen in UMCCR and this module is gonna be very useful for us, so perhaps it makes sense to have it in one way or another. Open to suggestions!

Screen Shot 2020-01-06 at 15 26 49

Full example report for a WGS tumor/normal variant calling pipeline:
[multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/4038848/multiqc_report.html.zip)

## If this PR is for a new module
 - [x] There is example tool output for tools in the https://github.com/ewels/MultiQC_TestData repository - https://github.com/ewels/MultiQC_TestData/pull/134
 - [x] Code is tested and works locally (including with `--lint` flag)
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated
 - [x] `docs/README.md` is updated with link to below
 - [x] `docs/modulename.md` is created
 - [x] Everything that can be represented with a plot instead of a table is a plot
 - [x] Report sections have a description and help text (with `self.add_section`)
 - [ ] There aren't any huge tables with > 6 columns (explain reasoning if so)
 - [x] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
 - [x] Module does not do any significant computational work

### CODE REVIEW

**Comment by vladsaveliev** [comment]
Attaching an example report for a WGS tumor/normal variant calling pipeline.
[MultiQC_Dragen_WGS_TN_varcall.html.zip](https://github.com/ewels/MultiQC/files/4024711/MultiQC_Dragen_WGS_TN_varcall.html.zip)

**Comment by ewels** [comment]
Oh no! How come you closed the PR and deleted the branch..? I was looking forward to reviewing / merging this!

**Comment by vladsaveliev** [comment]
I passed it by Illumina, will reopen after their review. Don’t worry :)

**Comment by vladsaveliev** [comment]
Shouldn't have deleted the branch though. But I recreated it, so you can take a look at diff. https://github.com/ewels/MultiQC/compare/master...vladsaveliev:dragen?expand=1
Will create a new PR I guess by the end the next week.

**Comment by ewels** [comment]
Ah ok, nice!

**Comment by ewels** [comment]
Wow, it’s a big one! Ok, I’m glad you found someone else to review it as well..! 😅

**Pull request closed without merging**
