### PR TITLE
Hicexplorer3

### PR DESCRIPTION
**Pull request by LeilyR**
Updated the format of the report to fits the changes which have been applied to the QC report of hicexplorer v3.3
Many thanks to contributing to MultiQC!

## If this PR is _not_ a new module
 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` has been updated
 - [x] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change

### CODE REVIEW

**Comment by joachimwolff** [comment]
@ewels I fixed our HiCExplorer and it is now compatible with all QC reports from all different versions. Concerning this, please merge: https://github.com/ewels/MultiQC_TestData/pull/141

I also set the versions for jinja2 and markdown to Python 2 compatible versions, this is currently failing in the master branch. However, the test cases fail caused by some broken modules like: gene_body_coverage, junction_saturation, MarkDuplicates, fastq_screen, afterqc, fastqc.

Would be great if you can make these run again or configure somehow the test cases in a way that we can show HiCExplorer module is passing its test cases.

Best,

Joachim

**Comment by joachimwolff** [comment]
@lukaw3d Your module fastq_screen is causing troubles, all test cases fail because the linting fails for your module. Fix it please!

**Comment by joachimwolff** [comment]
@ewels I commented the module `fastq_screen` in the setup.py out because it lead to linting failures. All test cases here pass now, would it be possible to merge this PR? 

It is, however, your decision to keep the faulty `fastq_screen` outcommented or to add it again before we merge this. 

Thanks a lot!

**Comment by ewels** [comment]
Hi @joachimwolff,

Thanks for your work on this! Apologies for the failing tests, I’ve been aware of this for a few weeks now and need to sort it out. I intend to drop official support for Python 2 now which I think should fix most of the problems.

I hope to get to MultiQC work soon, I’ve been getting a bit swept up in other surprise projects recently (these are strange times!) but I’ll do my best!

Phil

**Comment by ewels** [comment]
Thanks for this @LeilyR / @joachimwolff - I will merge this into a branch and then work on it a little myself to clean it up before merging to master. Basically reverting a couple of your fixes in the installation and FastQ Screen stuff and some minor formatting / cleanup.

**Pull request merged**
