### PR TITLE
Add fastp module

### PR DESCRIPTION
**Pull request by florianduclot**
In reference to #669 , this PR adds a new module for reports created by [Fastp](https://github.com/OpenGene/fastp).

In its current state, this module mostly parses the JSON report from fastp to populate the General statistics table, and generate a barplot for filtering metrics. Fastp report a lot of other information, but as most of these are redundant with other popular tools (such as FastQC--to some degrees), these may not be needed. Maybe this should be the subject of future update to this module?

With regards to the code, `fastp.py` is mostly based on the _afterqc_ module, to which _fastp_ is a successor (same author). As this is my first attempt at a module, and python to this extent, the code and approach may not be optimal. I'm especially wondering whether errors are handled the best way possible. Thanks for any pointers/suggestions.

This module has been tested with the example JSON report provided by _fastp_ ([here](http://opengene.org/fastp/fastp.html)), and verified to work on Python 2 and 3 (both manually and Travis).

Thanks for considering adding this module and for any suggestion for improvement.

### CODE REVIEW

**Comment by ewels** [comment]
Thanks for this @florianduclot! I'll get to reviewing it soon. Next couple of weeks are pretty packed but will be as quick as I can...

**Comment by ewels** [comment]
Many thanks again for this @florianduclot! It's a great start and looks good. I think I'd like to do a bit of refactoring and adding additional plots, so I've changed your PR to point to a dev branch for this module - hope this is ok! I'll merge there and then do some more work on it myself. I'll then open up a second PR and ping you for feedback.

Cheers,

Phil

**Comment by florianduclot** [comment]
Sounds good! Thanks for your time working on this!

As I briefly mentioned above, most plots could be considered redundant with other tools such as FastQC and that's why I didn't include them as I was worried it could make the multiqc report too busy by default for some. 
I do like the possibility to plot both read1 and read2 independently for most metrics, though, so I was entertaining this idea.
Looking forward to hearing more.
Cheers,

**Comment by ewels** [comment]
I kind of think that if the MultiQC report plot has these metrics and plots, then people don't need to run FastQC and the other similar tools? People can always easily disable modules if they want anyway, so I'm not too concerned by that.

**Pull request merged**
