### PR TITLE
Add initial AfterQC report

### PR DESCRIPTION
**Pull request by raonyguimaraes**
#462 Add initial AfterQC report of summary table.

### CODE REVIEW

**Comment by ewels** [comment]
Fantastic stuff, thanks @raonyguimaraes! I've gone through and made some edits of my own in commit https://github.com/ewels/MultiQC/commit/6b56da9d7e39643edcce6b7ccdfb198eeef25805 - I've covered this commit with comments explaining what I changed and why. Hopefully it all makes sense!

Thanks again for working on this. And yeah - if you fancy adding any additional plots or information then that would be great! Overlapping read information could be a good candidate...?

**Comment by raonyguimaraes** [comment]
I will see what I can do Phil, thanks for all the help today!

**Comment by marchoeppner** [comment]
Not sure this is the right place, but was trying to run this module on an AfterQC Json file and got this: 

multiqc F12505-L2_S32_L003_R1_001.fastq.gz.json

[INFO   ]         multiqc : This is MultiQC v1.2
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'F12505-L2_S32_L003_R1_001.fastq.gz.json'
Searching 1 files..  [####################################]  100%
[INFO   ]         afterqc : Found 1 reports
[WARNING]        bargraph : Tried to make bar plot, but had no data
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete


AfterQC version: 0.9.6
MultiQC: 1.2

And the JSON file definitely contains data, so unclear at the moment why this doesn't work for me. Any idea?

**Comment by marchoeppner** [comment]
And the JSON file: https://pastebin.com/p5LM4yLE

**Comment by ewels** [comment]
Thanks @marchoeppner - I'll pop this into a new issue if that's ok as I'm less likely to lose track of it there. Sounds like a bug though. Thanks for the example data 👍

**Pull request merged**
