### PR TITLE
AdapterRemoval: Fix the calculation of retained and discarded reads when option collapse is activated

### PR DESCRIPTION
**Pull request by alexhbnr**
Here is some suggestion how to fix the plotting of the number of reads that were processed by AdapterRemoval2 when the option "collapse" is activated, which particularly affects the number of retained and discarded reads (see issue here: #1005)

Briefly, it corrects the number of retained and discarded reads but subtracting the number of collapsed reads from it.

I am not sure, if this fixes all problems of this plot, but it would be a solution to start working from.

 - [x] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` has been updated

### CODE REVIEW

**Comment by apeltzer** [comment]
Can we merge this to a separate branch maybe so I can help on it? The discussion moved on quite a lot https://github.com/ewels/MultiQC/issues/1005 but maybe we can quickly realign here to get this into the next release? 
@ewels @alexhbnr ? Happy to aid in making this fixed in the upcoming release Alex, but cannot merge / change anything on your PR - either we discuss the last missing bits in the #1005 issue and you do it or we merge this PR to a separate branch that I can access too ;-)

**Comment by apeltzer** [comment]
Happy with both!

**Comment by alexhbnr** [comment]
Sorry for being a git noob, but if you tell me how I move it to a separate branch, I am happy to do it.
This sounds like the easiest solution.

**Comment by apeltzer** [comment]
> Sorry for being a git noob, but if you tell me how I move it to a separate branch, I am happy to do it.
> This sounds like the easiest solution.

Wrote you on mattermost 👍🏻

**Comment by jfy133** [comment]
@alexhbnr @apeltzer @ewels proposal here: https://github.com/ewels/MultiQC/issues/1005#issuecomment-791238512

**Comment by ewels** [comment]
Solved by https://github.com/ewels/MultiQC/pull/1647

**Pull request closed without merging**
