### PR TITLE
Add . or _ to search patterns for quant metrics csv

### PR DESCRIPTION
**Pull request by alexiswl**
Patch from #1958

### CODE REVIEW

**Comment by ewels** [comment]
Hi @alexiswl - did you test this and it's definitely working? `fn` is a glob, not regex. I always have to google syntax but off the top of my head I thought it was squiggly brackets for this? But maybe square brackets work for glob syntax too..

**Comment by vladsavelyev** [comment]
@ewels I tested it on my side and it worked well, but I agree that it would be nice to add test examples into `MultiQC_TestData` for `dragen/rna_quant_metrics` module. 

Also, it looks like the `parse_time_metrics_file` method was copied from `time_metrics.py`, I think it should be renamed, and the example data in the docstring should be updated. I'll do that now, but agree it would also be nice to refactor the Dragen modules to use cleaning patterns.

**Comment by ewels** [comment]
Sounds good, thanks! Yeah a lot of the DRAGEN code is quite non-standard. Makes maintenance a bit of a headache..

**Comment by alexiswl** [comment]
> Hi @alexiswl - did you test this and it's definitely working? fn is a glob, not regex. I always have to google syntax but off the top of my head I thought it was squiggly brackets for this? But maybe square brackets work for glob syntax too..

I just ran a python regex over it and also used the same syntax as https://github.com/alexiswl/MultiQC/blob/bc4f724abf9e60deb0e335c57a6d76ef284a4845/multiqc/utils/search_patterns.yaml#L303-L306

**Pull request merged**
