### PR TITLE
Updated hicexplorer search patterns, compatible with previous versions

### PR DESCRIPTION
**Pull request by jakevc**
Many thanks to contributing to MultiQC!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things I request on pull requests (PRs).

## If this PR is _not_ a new module
 - [X] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` has been updated
 - [X] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change

## If this PR is for a new module
 - [ ] There is example tool output for tools in the https://github.com/ewels/MultiQC_TestData repository
 - [ ] Code is tested and works locally (including with `--lint` flag)
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated
 - [ ] `docs/README.md` is updated with link to below
 - [ ] `docs/modulename.md` is created
 - [ ] Everything that can be represented with a plot instead of a table is a plot
 - [ ] Report sections have a description and help text (with `self.add_section`)
 - [ ] There aren't any huge tables with > 6 columns (explain reasoning if so)
 - [ ] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
 - [ ] Module does not do any significant computational work

### CODE REVIEW

**Comment by jakevc** [comment]
Fixes https://github.com/ewels/MultiQC/issues/893

**Comment by ewels** [comment]
Hi @jakevc,

Can you explain how this fixes the error in #893? I don't see how changing the search pattern would make any difference..?

Phil

**Comment by jakevc** [comment]
The log files produced by hicBuildMatrix of hicexplorer=v2.2, produces a new log file QC_table.txt with a format not designed to be parsed by this module. It looks like the log file that was designed to be parsed by this module is QC.log(v2.2,v1.8,v1.7), or QC.txt(v2.0).

**Comment by ewels** [comment]
Ok gotcha, thanks for the explanation 👍 

This filename fix is good, but it would be nice to also put something into the Python code to specifically ignore these new log files. People can (and often do) create their own search configs so it's good to be able to reject these from within the parsing code as a fallback.

Are you ok to add that to this PR as well? It could just be searching the file for a string that is unique to the file that we want to ignore (eg. `mappable, unique and high quality pairs` or something).

Phil

**Comment by jakevc** [comment]
Okay great, I'll work on a more robust and integrated solution.
Thanks,
JVC

**Comment by ewels** [comment]
No need to revert the search pattern change - that was good! Just an extra backup in the code would be a good bonus feature 🚀

**Comment by jakevc** [comment]
This new change made it so we don't need the search pattern. Should it still be included?

**Comment by ewels** [comment]
Ok great 👍

**Pull request merged**
