### PR TITLE
Replace deprecated logger.warn with logger.warning (Fixes #1138)

### LINKED ISSUE #1138: Use log.warning instead of log.warn
New global warn log seems to be coming from the `logging` module, see https://github.com/ewels/MultiQC/issues/1126:

```
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn('MultiQC Version {} now available!'.format(remote_version))
```

Need to so some find+replace to switch out all occurrences of `warn`.

### PR DESCRIPTION
**Pull request by cpavanrun**
Fixes #1138 via:

```bash
grep -irl 'logger.warn(' * | xargs sed -i 's/logger.warn(/logger.warning(/g'
```

## If this PR is _not_ a new module

 - [ ] This comment contains a description of changes (with reason)
 - [X] `CHANGELOG.md` has been updated
 - [ ] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change

### CODE REVIEW

**Comment by ewels** [comment]
Ah nice, thank you! Been meaning to do this for a while.

I think you're missing quite a lot of `log.warn()` statements as well (versus `logger.warn()`)

Most of the modules import the logger as `log`:

```python
# Initialise the logger
log = logging.getLogger(__name__)
```

**Comment by ewels** [comment]
Yeah, 13 > 48 changes with those additional ones added in 👍  Hopefully that's all of them..

**Comment by ewels** [comment]
My approach was a little more low-skilled 😅 

image

**Comment by ewels** [comment]
Any ideas how we can test for this to avoid people (me) accidentally using `log.warn()` again in the future?

**Comment by cpavanrun** [comment]
@ewels, why bother testing it? warn() will become unusable anyway =). Deprecation warnings are in general a pre-empt. Which are nice to pick up on but I wouldn't have tests fail on it. Eventually a package will force you to fix it anyway.

**Comment by ewels** [comment]
Fair enough, good point!

**Pull request merged**
