### PR TITLE
handle kreports with all unclassified reads

### PR DESCRIPTION
**Pull request by jchorl**
Fixes https://github.com/ewels/MultiQC/issues/1637

If the whole file is unclassified, we omit top-5 data from general stats. We also make sure unclassified isn't duplicated in the Top taxa table.

- [x] Kraken module can now handle kreports with all unclassified reads (bugfix)
- [x] `CHANGELOG.md` has been updated

### CODE REVIEW

**Comment by schorlton** [comment]
Hi @ewels, bumping this - thanks!

**Comment by Midnighter** [comment]
Just wanted to report a scenario here (maybe you have already considered it) where the current output doesn't show the unclassified reads for some reason.

kraken2 report:
```tsv
100.00	16255900	16255900	0	0	U	0	unclassified
  0.00	150	0	28251	13056	R	1	root
  0.00	150	0	28251	13056	R1	131567	  cellular organisms
  0.00	150	0	28251	13056	D	2759	    Eukaryota
  0.00	150	0	28251	13056	D1	33154	      Opisthokonta
  0.00	150	0	28251	13056	K	33208	        Metazoa
  0.00	150	0	28251	13056	K1	6072	          Eumetazoa
  0.00	150	0	28251	13056	K2	33213	            Bilateria
  0.00	150	0	28251	13056	K3	33511	              Deuterostomia
  0.00	150	0	28251	13056	P	7711	                Chordata
  0.00	150	0	28251	13056	P1	89593	                  Craniata
  0.00	150	0	28251	13056	P2	7742	                    Vertebrata
  0.00	150	0	28251	13056	P3	7776	                      Gnathostomata
  0.00	150	0	28251	13056	P4	117570	                        Teleostomi
  0.00	150	0	28251	13056	P5	117571	                          Euteleostomi
  0.00	150	0	28251	13056	P6	8287	                            Sarcopterygii
  0.00	150	0	28251	13056	P7	1338369	                              Dipnotetrapodomorpha
  0.00	150	0	28251	13056	P8	32523	                                Tetrapoda
  0.00	150	0	28251	13056	P9	32524	                                  Amniota
  0.00	150	0	28251	13056	C	40674	                                    Mammalia
  0.00	150	0	28251	13056	C1	32525	                                      Theria
  0.00	150	0	28251	13056	C2	9347	                                        Eutheria
  0.00	150	0	28251	13056	C3	1437010	                                          Boreoeutheria
  0.00	150	0	28251	13056	C4	314146	                                            Euarchontoglires
  0.00	150	0	28251	13056	O	9443	                                              Primates
  0.00	150	0	28251	13056	O1	376913	                                                Haplorrhini
  0.00	150	0	28251	13056	O2	314293	                                                  Simiiformes
  0.00	150	0	28251	13056	O3	9526	                                                    Catarrhini
  0.00	150	0	28251	13056	O4	314295	                                                      Hominoidea
  0.00	150	0	28251	13056	F	9604	                                                        Hominidae
  0.00	150	0	28251	13056	F1	207598	                                                          Homininae
  0.00	150	0	28251	13056	G	9605	                                                            Homo
  0.00	150	150	28251	13056	S	9606	                                                              Homo sapiens
```

Display:

image

Under normal circumstances I see a bar for the unclassified reads, too.

**Comment by Midnighter** [comment]
I expected to see something like this:

image

**Comment by ewels** [comment]
@Midnighter - I think I figured it out. It's because your % undetermined was 100.0% and the regular expression didn't expect three digits.

Hopefully fixed now, appended to this PR. Shout if I broke anything.

Thanks all!

**Pull request merged**
