### PR TITLE
Updated cli and logging

### PR DESCRIPTION
**Pull request by moonso**
- Updated cli, uses click
- Moved code out of __init__ according to https://www.python.org/dev/peps/pep-0008/ (this should be done in the modules to, but that will be next pull request:)
- Use proper loghandler in multiqc/log.py
- import modules in __init__ instead of run script for more clean code

### CODE REVIEW

**Comment by moonso** [comment]
Saw that the test failed. Couldn't find any tests in the repo but when I tried my branch with your test data it worked fine...

**Comment by moonso** [comment]
Missed to include click to dependencies, works now:)

**Comment by ewels** [comment]
This is awesome! I really like the reorganisation, makes the code much easier to navigate. Had a quick look through - as you suggested, I think it's probably best if we chat through the code over a fika.. (There are a few obscure bits you've commented out that need explaining, plus some stuff I don't understand).

**Comment by moonso** [comment]
Ok glad you liked it! 
This afternoon?

**Comment by ewels** [comment]
To-do list based on our conversation:

- [ ] Remove [debugging print](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L39-L40) statements
- [ ] Get the version of the package in the `__init__.py` (from the setup) rather than explicitly listing twice
- [ ] Allow multiple analysis directories to be given (positional, not flag arguments)
  - See [this](http://stackoverflow.com/questions/7588620/os-walk-multiple-directories-at-once)
- [ ] Update the version code to be like [TACA](https://github.com/SciLifeLab/TACA/blob/master/taca/cli.py#L17)
- [ ] Remove [commented out code](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L42-L62)
- [ ] Better [docstring](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L118)
- [ ] Import [this](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L119) at the top...?
- [ ] Move [this](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L124-L128) into the `__init__.py` stuff.
- [ ] Keep [this](https://github.com/ewels/MultiQC/blob/master/scripts/multiqc#L191) in, maybe with a comment to apologise
- [ ] Avoid overwriting `module` variable name [here](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L197)
- [ ] Try to avoid having multiple variables that are _almost_ the same thing. [This](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L84) is not ordered. We have `module`, `run_modules`, `avail_mods` and `module_submods` or something.
- [ ] Delete all of the commented out code.

Hopefully not as bad as it looks!

**Comment by moonso** [comment]
To-do list based on our conversation:

- [ ] Remove [debugging print](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L39-L40) statements
- [ ] Get the version of the package in the `__init__.py` (from the setup) rather than explicitly listing twice
- [ ] Allow multiple analysis directories to be given (positional, not flag arguments)
  - See [this](http://stackoverflow.com/questions/7588620/os-walk-multiple-directories-at-once)
- [ ] Update the version code to be like [TACA](https://github.com/SciLifeLab/TACA/blob/master/taca/cli.py#L17)
- [ ] Remove [commented out code](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L42-L62)
- [ ] Better [docstring](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L118)
- [ ] Import [this](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L119) at the top...?
- [ ] Move [this](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L124-L128) into the `__init__.py` stuff.
- [ ] Keep [this](https://github.com/ewels/MultiQC/blob/master/scripts/multiqc#L191) in, maybe with a comment to apologise
- [ ] Avoid overwriting `module` variable name [here](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L197)
- [ ] Try to avoid having multiple variables that are _almost_ the same thing. [This](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L84) is not ordered. We have `module`, `run_modules`, `avail_mods` and `module_submods` or something.
- [ ] Delete all of the commented out code.

Hopefully not as bad as it looks!

**Comment by moonso** [comment]
To-do list based on our conversation:

- [ ] Remove [debugging print](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L39-L40) statements
- [ ] Get the version of the package in the `__init__.py` (from the setup) rather than explicitly listing twice
- [ ] Allow multiple analysis directories to be given (positional, not flag arguments)
  - See [this](http://stackoverflow.com/questions/7588620/os-walk-multiple-directories-at-once)
- [ ] Update the version code to be like [TACA](https://github.com/SciLifeLab/TACA/blob/master/taca/cli.py#L17)
- [ ] Remove [commented out code](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L42-L62)
- [ ] Better [docstring](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L118)
- [ ] Import [this](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L119) at the top...?
- [ ] Move [this](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L124-L128) into the `__init__.py` stuff.
- [ ] Keep [this](https://github.com/ewels/MultiQC/blob/master/scripts/multiqc#L191) in, maybe with a comment to apologise
- [ ] Avoid overwriting `module` variable name [here](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L197)
- [ ] Try to avoid having multiple variables that are _almost_ the same thing. [This](https://github.com/moonso/MultiQC/blob/258a45d6f72a5d4278b6c4b326547d1e012cb668/scripts/multiqc#L84) is not ordered. We have `module`, `run_modules`, `avail_mods` and `module_submods` or something.
- [ ] Delete all of the commented out code.

Hopefully not as bad as it looks!

**Comment by moonso** [comment]
Hey!

I did most of the fixes but I skipped the "multiple analysis dir"-thing.
That should be another pull request.

**Comment by ewels** [comment]
Awesome - fast work! Thanks again, this is starting to feel like much cleaner code now...

**Comment by moonso** [comment]
:+1:

**Pull request merged**
