### PR TITLE
Fix issue 1133: RSeqC junction saturation compatibility with toolbox

### PR DESCRIPTION
**Pull request by sergpolly**
as described in #1133 - this is just a quick fix to the JavaScript side of things:
 - explicitly take sample renaming into account (the only caveat is degenerate sample renaming situtaion)
 - make an attempt to handle the situation when toolbox-changes are applied, while single-sample/side-by-side view is open - I copy-pasted the `"return to overview"` button behavior
 - other than that - no changes in regards with `hide/highlight` - these are more questionable
 - I also moved all of js code to `assets/js/multiqc_rsec.js` in the best traditions of `fastqc` module - otherwise it was really inconvenient to work with javascript stuff

here is a little screencast after the fix:
fixed

## If this PR is _not_ a new module
 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` has been updated
 - [x] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change

### CODE REVIEW

**Comment by ewels** [comment]
Thanks for this @sergpolly! I guess [this](https://github.com/ewels/MultiQC/pull/1134/files/e231ffcb89d4bd5cf074cbbf29f6cbc04b3b481f..ec52afcc10cbc199a1cb7aac4f6fe47caf8b3760) is the relevant diff for the code changes? That is, you only moved code in e231ffc and didn't change anything?

**Comment by sergpolly** [comment]
Hi @ewels !
> Thanks for this @sergpolly! I guess [this](https://github.com/ewels/MultiQC/pull/1134/files/e231ffcb89d4bd5cf074cbbf29f6cbc04b3b481f..ec52afcc10cbc199a1cb7aac4f6fe47caf8b3760) is the relevant diff for the code changes? That is, you only moved code in [e231ffc](https://github.com/ewels/MultiQC/commit/e231ffcb89d4bd5cf074cbbf29f6cbc04b3b481f) and didn't change anything?

yes, you are absolutely right!
I didn't know one could generate a url to show diffs for a subset of commits - [this](https://github.com/ewels/MultiQC/pull/1134/files/e231ffcb89d4bd5cf074cbbf29f6cbc04b3b481f..ec52afcc10cbc199a1cb7aac4f6fe47caf8b3760) - shows it all.

 - [e231ffc](https://github.com/ewels/MultiQC/commit/e231ffcb89d4bd5cf074cbbf29f6cbc04b3b481f) is just moving the previous `onclick` function to "assets", I think it relatively cleanly done - following "traditions" of the `fastqc` module. We could totally revert this one, it was just much easier to debug this way - instead of editing directly in the string variable holding JS code (or even copy pasting code back and forth)
 - the actual [changes](https://github.com/ewels/MultiQC/pull/1134/files/e231ffcb89d4bd5cf074cbbf29f6cbc04b3b481f..ec52afcc10cbc199a1cb7aac4f6fe47caf8b3760) come down to:
    - 1 helper function that takes care of renaming
    - taking care of renaming on two occasions - when we extract `data` per sample in defaults behavior and when we do it for `Prev`/`Next` buttons
    - event listener to make sure single sample view "slides away" when another toolbox operation is applied (and re-draw is triggered in the parent plotting function) - I'm in doubt about that one, because I've simply wrapped the `Back to overview` [behavior](https://github.com/ewels/MultiQC/blob/661f82d75ca9f0fe96a9c31c5ac41f7cba7e8310/multiqc/modules/rseqc/junction_saturation.py#L148) into `$(document).on('mqc_highlights mqc_renamesamples mqc_hidesamples', function(e)` event listener (taken from elsewhere in multiqc code)


- what I haven't addressed at all is "highglight/hide" functionality here:
    - do one really need "hide/highlight" for singe-sample sneak-peek ?  - probably "yes" for consistency, likely "no" for functionality of it ...
    - when single-sample `onclick` is activated while `hide` is applied - it should affect the `Prev`/`Next` button, i.e. we shouldn't toggle through hidden samples
    - how would "highlight" work? - change colors when toggling through samples ?

What do you think about this "highlight/hide" dilemma ?

**Comment by sergpolly** [comment]
Hi @ewels 
I addressed "hide/highlight" in a way ...

1. when hiding enabled - clicking `Prev/Next` in a single sample view - user isn't gonna see hidden items. "XXX Samples are hidden" banner is there from the parent object - so i think it's cool, Ok at least
2. "Highlighting" highlights the sample name not the data curves themselves - it is questionable , I agree, but it is acknowledging the highlighting functionality in some way at least

here is the demo:
rseqc_full

please let me know what you think about this solution ?

**Comment by ewels** [comment]
Hi @sergpolly,

I've made it to your PR at last, sorry for the delay. There's a merge conflict in `CHANGELOG.md` now sorry - I tried to fix it but it looks like I don't have permission to push to your branch (the little _"Allow edits from maintainers."_ checkbox I assume).

Anyway, if you could please pull in upstream changes from `master` and fix the merge conflict that'd be great, hopefully then the CI tests will pass.

Phil

**Comment by ewels** [comment]
And yes, I think the solutions you've come to for highlighting and hiding sound spot on 👍

**Comment by ewels** [comment]
ok, tested locally and works like a charm, so merged 👍 

Thank you for this! Lovely job!

**Comment by sergpolly** [comment]
hm, actually I don't have that "Allow edits from maintainers" checkbox ... maybe because our multiqc fork is organization-owned, not my personal one - as github docs describe it [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) ...

i couldn't think of anything else ... uh oh

anyhow, thank you for merging @ewels !

**Comment by ewels** [comment]
Ah ok, that would explain it. Didn’t matter at all in the end as I didn’t need to change anything for the merge really, so was fine. I’ve just been enjoying my new workflow of using the new `gh` command line tool to check out PRs and then edit & push them. It’s fab!

**Pull request merged**
