### PR TITLE
Mini sidenav

### PR DESCRIPTION
**Pull request by ewels**
Made a narrow version of the main side navigation. Has a button to toggle between this and the previous wider version.

### CODE REVIEW

**Comment by ewels** [comment]
Hi @avilella @s-andrews @FelixKrueger @guillermo-carrasco and others,

I just made a narrow version of the side nav. I quite like it, I'm thinking of making it the default.

There's a demo here: http://multiqc.info/narrow_nav.html - any feedback?

Phil

**Comment by s-andrews** [comment]
Sorry, but I think it's less intuitive than the previous version.  Without the program names it's not clear what those buttons are for.  Also, having 3 buttons with just F (or f) on them isn't a great UI.

**Comment by avilella** [comment]
Maybe just a toggle button that flips it from side to top (e.g. mobile
orientation) would do.

**Comment by avilella** [comment]
I made a point release for our Data Analysis doc based on this branch:

pip install --user --upgrade
https://github.com/avilella/MultiQC/archive/ce-multiqc-v20151111.zip

Thx @ewels!

**Comment by ewels** [comment]
Thanks @s-andrews - good feedback. Maybe midnight on a moving bus wasn't the best time to make design decisions about this. It started off as blobs which I then converted into single letter icons. Looking at it this morning I wonder if I'd be better off just keeping the old nav, but converting it into an off-canvas navigation (something like [this](http://foundation.zurb.com/docs/components/offcanvas.html)). Would that be better?

@avilella - I'm a bit confused about your point release comment, what do you mean exactly? Why can't you just describe it as `pip install --user multiqc`? I'd prefer not to refer to forks of the code for released documentation if possible, as it makes it harder for people to keep up to date with the main repository. If you want CEGX customisation it would be better to make your own plugin package.

**Comment by s-andrews** [comment]
To be honest I quite liked the old version :-)

I¹m not entirely sure what problem needed to be fixed with that.

Simon.

From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/MultiQC
<reply+007c7ae3e659def119b40d82d8ac8c343f54aa9f4e7e918992cf00000001125ac61b9
2a169ce06ed7abf@reply.github.com>
Date:  Wednesday, 11 November 2015 09:02
To:  ewels/MultiQC <MultiQC@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>
Subject:  Re: [MultiQC] Mini sidenav (#105)


Thanks @s-andrews <https://github.com/s-andrews>  - good feedback. Maybe
midnight on a moving bus wasn't the best time to make design decisions about
this. It started off as blobs which I then converted into single letter
icons. Looking at it this morning I wonder if I'd be better off just keeping
the old nav, but converting it into an off-canvas navigation (something like
this <http://foundation.zurb.com/docs/components/offcanvas.html> ). Would
that be better?

@avilella <https://github.com/avilella>  - I'm a bit confused about your
point release comment, what do you mean exactly? Why can't you just describe
it as pip install --user multiqc? I'd prefer not to refer to forks of the
code for released documentation if possible, as it makes it harder for
people to keep up to date with the main repository. If you want CEGX
customisation it would be better to make your own plugin package.


Reply to this email directly or view it on GitHub
<https://github.com/ewels/MultiQC/pull/105#issuecomment-155709210> .

**Comment by avilella** [comment]
@ewels, that's the best version we want to offer our users in our bundle at
the moment.

Happy to revert back to master or a proper release soon.

Not that a lot of people download the bundle, mind you:
https://bitbucket.org/cegx-bfx/ce/downloads

**Comment by ewels** [comment]
@s-andrews - I like the old version as well, I don't intend to remove that. But @avilella has a point that it takes up a fair bit of space, especially if the window is narrow. Maybe that would be the best solution - have an off-canvas menu, but only if the screen width is less than a certain amount. Then there would be no change for most people, but it would be out of the way when it's annoying.

@avilella - if your new code is ready for release then can you merge it back into the main repo via a pull request so that it's available for everyone?

**Comment by ewels** [comment]
Ok, I simplified things a bit - demo now updated: http://multiqc.info/narrow_nav.html

* No "mini" nav any more with single letter icons or anything
* New button on left nav now just hides nav (always shown by default)
* Mobile layout has been cleaned up quite a bit. Now collapsable and hidden by default on tiny screens.

**Comment by ewels** [comment]
Happy with this now I think. Merging.

**Comment by ewels** [comment]
Deleted the narrow nav example report - it's now the example that's used on the homepage though:
http://multiqc.info/examples/rna-seq/multiqc_report.html

**Comment by s-andrews** [comment]
Ok, I simplified things a bit - demo now updated:
http://multiqc.info/narrow_nav.html

404?

**Comment by s-andrews** [comment]
Shouldn¹t the toolbox expand when you click on the bit which says ³Toolbox²
as well?


From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/MultiQC
<reply+007c7ae32783c8b8d2834c085ee87d96f9fda8b95dc211e092cf00000001125c46f39
2a169ce06ed7abf@reply.github.com>
Date:  Thursday, 12 November 2015 12:24
To:  ewels/MultiQC <MultiQC@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>
Subject:  Re: [MultiQC] Mini sidenav (#105)


Deleted the narrow nav example report - it's now the example that's used on
the homepage though:
http://multiqc.info/examples/rna-seq/multiqc_report.html


Reply to this email directly or view it on GitHub
<https://github.com/ewels/MultiQC/pull/105#issuecomment-156090954> .

**Comment by ewels** [comment]
Yup - 404 because I deleted it (see above comment) - now at http://multiqc.info/examples/rna-seq/multiqc_report.html

I could make the `toolbox` text bit into a button, yup. I haven't changed that code in this PR but will make the change now.

**Comment by ewels** [comment]
Done in 85d1923f301bcc92ff08ab2a3f24414c49b287d5

**Comment by avilella** [comment]
This looks perfectly good to me:

 http://multiqc.info/examples/rna-seq/multiqc_report.html

A.

**Comment by ewels** [comment]
Nice! Demo (that link) updated with new `toolbox` button that opens / closes toolbox.

**Pull request merged**
