### PR TITLE
phantompeakqualtools, more deeptools, miRTrace tweak

### PR DESCRIPTION
**Pull request by chuan-wang**
Many thanks to contributing to MultiQC!

Description of changes:
1) For miRTrace, add a colon in plot title for complexity plot;
2) For phantompeakqualtools, add Add function for plotting strand correlation plot

## If this PR is _not_ a new module
 - [X] This comment contains a description of changes (with reason)
 - [X] `CHANGELOG.md` has been updated
 - [X] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change

### CODE REVIEW

**Comment by chuan-wang** [comment]
There is still bug with the plotPCA submodule for deepTools. I will continue with it tomorrow.

**Comment by chuan-wang** [comment]
Bug fixed. Code worked as expected.

**Comment by chuan-wang** [comment]
Close issue https://github.com/nf-core/chipseq/issues/23

**Comment by chuan-wang** [comment]
Hi @ewels, I'm done with this PR. The category solution didn't work as it will break the background colors. We can put any improvement in the next PR.

**Comment by ewels** [comment]
> The category solution didn't work as it will break the background colors

Note that when you use categories, the x "numbers" change from whatever they were previously (eg. 0-4000 or whatever) to simple counts of each category (eg. 0-250). I _think_ that they should still work in principle. But I may be wrong 😀 

Anyway, thanks! I will now get to work on splitting this PR up and reviewing it 👍

**Comment by chuan-wang** [comment]
Hi @ewels, I fixed the X axis in the latest commit. Are you coming to office today? I may have noticed a bug in MultiQC.

**Comment by chuan-wang** [comment]
Hi @ewels, I realized that the so-called "bug" was simply a result of `smooth_point`. There is no more issue with this PR.

**Comment by ewels** [comment]
Ah good :) That was the first thing I was going to check.. 😉

**Pull request merged**
