### PR TITLE
Add PURPLE module

### PR DESCRIPTION
**Pull request by vladsaveliev**
Adding a module for [PURPLE](https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator) -  a purity, ploidy and copy number caller for whole genome tumor data.

In terms of QC, we mainly use several metrics that the tool reports in two files, and they fit into a table very well. The table ended up having 10 columns, but they are very different and readable to my taste, so might be not a big deal that it's longer than 6 cols, I hope:

Screen Shot 2020-07-11 at 00 12 44
 
PURPLE also generates [some plots](https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#charts) that might be tricky to reimplement with highcharts though (and computationally intensive), so not sure if it's needed.

 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` has been updated

 - [x] There is example tool output for tools in the https://github.com/ewels/MultiQC_TestData repository or attached to this PR
 - [x] Code is tested and works locally (including with `--lint` flag)
 - [ ] `docs/README.md` is updated with link to below
 - [x] `docs/modulename.md` is created
 - [x] Everything that can be represented with a plot instead of a table is a plot
 - [x] Report sections have a description and help text (with `self.add_section`)
 - [ ] There aren't any huge tables with > 6 columns (explain reasoning if so)
 - [x] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
 - [x] Module does not do any significant computational work

### CODE REVIEW

**Comment by ohofmann** [comment]
cc @jonbaber @p-priestley

**Comment by ewels** [comment]
Hi @vladsaveliev - sorry I'm being slow here, been a busy time recently with @nf-core and conferences etc. I'm about to go on holiday, but when I get back MultiQC is at the top of the pile again, so stay tuned.

Phil

**Review by ewels — APPROVED** [review]
A few minor tweaks pushed to the PR, but all looking great now!

Thanks for the contribution, sorry for the time it took me to get to it.

**Comment by ohofmann** [comment]
Yay! Thanks Vlad and Phil :)

**Pull request merged**
