### PR TITLE
BBmap

### PR DESCRIPTION
**Pull request by ewels**
Clean bbmap PR with tweaks from Phil before final merge.

### CODE REVIEW

**Comment by ewels** [comment]
Ok, I'm happy with this now - thanks for all of your hard work @boulund and @epruesse! Still a few things to work out (eg. difference between `Base quality` and `Sequence Quality` and more help text on table headers) but I think this is a good point to merge into the main release.

**Comment by nick-youngblut** [comment]
Just to check: the main page link to bbmap documentation (http://multiqc.info/docs/#bbmap) doesn't link to any bbmap documentation. Is the documentation somewhere else or has it not been added yet?

**Comment by ewels** [comment]
Ping @bouland

**Comment by ewels** [comment]
Ping @boulund

**Comment by boulund** [comment]
Hi!

Unfortunately, there is very little documentation for the BBMap module right now. You are all welcome to help improve it! 
Not sure if I was supposed to do something else than just create https://github.com/ewels/MultiQC/blob/master/docs/modules/bbmap.md. Do I need to link it from the main documentation somehow?

**Comment by ewels** [comment]
Ah apologies, I misunderstood the question. Yes, @boulund you need to add reference to the bbmap docs readme file in the YAML frontmatter here: https://github.com/ewels/MultiQC/blob/master/docs/README.md (see others for examples).

Apologies, I should have picked up on this in the PR review.

Phil

**Comment by boulund** [comment]
No problems! I must've missed that in the module creation instructions. Submitted a mini-PR with that change now (don't know if I could have done it as part of this PR somehow? I'm not on my work computer so figured I'd do it as simple as possible via the browser).

**Comment by ewels** [comment]
Thanks! No, once a PR is merged you can't do anything more with it..

[Link now working](http://multiqc.info/docs/#bbmap) @nick-youngblut 👍🏻

**Pull request merged**
