### PR TITLE
Sample filters with regex

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
- [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` has been updated

As discussed in on gitter. I added the option to have regex buttons. I kinda lazily just added another variable which keeps track of whether or not regex is required. 

I am not entirely sure if the way I grab the regex button is robust, I am not a javascript person :). 

Pinging @karl616 as he might be interested + willing to test?

### CODE REVIEW

**Comment by karl616** [comment]
@Maarten-vd-Sande I have put it on my agenda to test this... Need to find time though :) Looks like what I was looking for though. Thanks!

**Comment by Maarten-vd-Sande** [comment]
I deleted the repository :facepalm: , not sure how this would work with edits now..

**Comment by ewels** [comment]
> _I deleted the repository_

hah, this is a new one! 😆

**Review by ewels — APPROVED** [review]
Tested, works great! 🚀

**Comment by ewels** [comment]
This is fab - sorry for the long delay with reviewing!

**Pull request merged**
