### PR TITLE
solved breakdown bcftools

### PR DESCRIPTION
**Pull request by BiscuitCandy**
modified '/multiqc/modules/bcftools/stats.py'

### CODE REVIEW

**Review by ewels — CHANGES_REQUESTED** [review]
Could you explain your logic here please?

I don't think that this will work as it stands, as it will replace integers with `0.0`, which is wrong.

**Comment by BiscuitCandy** [comment]
> Could you explain your logic here please?
> 
> I don't think that this will work as it stands, as it will replace integers with `0.0`, which is wrong.

About that,

if the given parameter contains "." *(i.e decimal point)* then it adds a `0 at the front and a 0 at the end`
that means if the parameter is "5.2" then it becomes "05.20" and if the parameter is "." then it becomes "0.0"
**And it works if the parameter has a decimal point**

**Comment by BiscuitCandy** [comment]
> The latest commit is valid for natural numbers too
> Here it just adds a *0* at the start thus leaving the value unchanged 

 `let the parameter be 548 then it becomes float("0548") i.e 548.0` 
 `Or if the parameter is "." then it becomes float("0.")`

**Comment by ewels** [comment]
Ok nice, the update code looks good! A more elegant approach than just capturing the error as I had expected.

If you can just format with Black to get the tests to pass then I think we're good to go. Docs: https://multiqc.info/docs/#black

**Comment by BiscuitCandy** [comment]
`It's Done`

**Review by ewels — APPROVED** [review]
Perfect, thanks! 👍🏻

**Pull request merged**
