### PR TITLE
Cellranger module

### PR DESCRIPTION
**Pull request by ewels**
Continuation of PR #1689 as I don't have push access to HTGenomeAnalysisUnit/MultiQC.git so can't work on the PR to get it merged.

### CODE REVIEW

**Comment by ewels** [comment]
@edg1983 I've just started looking at the outputs from this module, and I'm half wondering if it should really be two modules: `Cell Ranger` and `Cell Ranger V(D)J`. They seem quite distinct in the two sets of outputs, and also in [the](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-cell-ranger) [docs](https://support.10xgenomics.com/single-cell-vdj/software/pipelines/latest/using/vdj).

What do you think?

**Comment by edg1983** [comment]
@ewels cellranger is a tool with multiple analysis modes. The most popular is count for sure, then VDJ generates a similar output in terms of the HTML report, and we use it often here so I've integrated this one as well. However, there are also other modalities like multi but the output of them is more complex to summarise. Given that the scope of the count and VDJ analysis is quite different, I agree that it makes sense to split them in separate modules. I don't have much time right now to work on this, but I can come back to it at the beginning of the next year.

**Comment by ewels** [comment]
Thinking about it with a fresh set of eyes this morning I think it's probably best structured as you have done. Thought it looked a bit odd with the different outputs in one module, but I guess it'll be rare for people to have both in one MultiQC report.. (?) so probably doesn't matter.

Having it as one module with the "Cell Ranger" name is probably clearest for people and easiest to maintain 👍🏻

**Comment by edg1983** [comment]
I can see a point in both approaches. 
Keeping both VDJ and count under a single cellranger module seems more in line with what you have so far for other modules, which are organized mainly by tool. One may perform a multi-modal experiment and then use multiple instances of cellranger. Still, I agree that it's not a typical scenario, and it is more likely to be analyzed using cellranger multi, which is not managed by this module anyway.

**Comment by ewels** [comment]
@edg1983 one of the requirements for MultiQC modules is that table columns have customised colour scales. This is to infer whether a value is good or not (eg. red - yellow - green) and also makes it much easier to spot small numeric differences quickly. Finally, it makes it easier to quickly scan reports and recognise columns.

I've refactored your code to take a dict of colour scales (see the [docs](https://multiqc.info/docs/#table-colour-scales-1) for available names) and made a start. It's getting late though so I need to stop. Any help would be much appreciated!

**Comment by ewels** [comment]
Ok, I'm happy with this now.

Still have a niggling feeling that we could be doing more with plots, but can't find anything better for now. I tried a heatmap for showing the percentage stats on the VDJ report but it was pretty awful, with one sample at least, so I didn't push that.

Many thanks @edg1983!

**Pull request merged**
