### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by vladsavelyev**
Screenshot 2023-10-13 at 10 54 44

### CODE REVIEW

**Review by ewels — APPROVED** [review]
Good to merge on Monday morning 👍🏻

**Comment by vladsavelyev** [comment]
Sign, nothing in ASCII the resembles the new logo indeed. The "handle" of the "magnifier" is of a shape of a back slash a bit, but that's too much of a stretch 😅

**Comment by ewels** [comment]
As with https://github.com/nextflow-io/nextflow/pull/4407#discussion_r1358825155, part of me wants a logo on the readme with some padding. But very very minor point.

**Comment by ewels** [comment]
@multiqc-bot changelog

**Comment by vladsavelyev** [comment]
Trying some padding with nbsp:

(before)

Screenshot 2023-10-16 at 12 07 36

(after)

Screenshot 2023-10-16 at 12 08 24

Honestly, I like the crammed version a bit more. But maybe could meet half-way. GitHub doesn't seem to allow padding around images, but could add some to the actual png instead.

**Review by ewels — APPROVED** [review]
LGTM! 👍🏻

**Pull request merged**
