### PR TITLE
Fix QualiMap MEAN/MEDIAN

### PR DESCRIPTION
**Pull request by apeltzer**
Hi,

this fixes a bug introduced in MultiQC v1.8 while adding the mean coverage computation to the QualiMap module output. Unfortunately, the `break` condition caused some errors and I had to split up the loop over the dictionary to two loops now to get this done correctly. I verified using the data in the #1082 issue and it looks like this fixed the problem. 

[multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/3978560/multiqc_report.html.zip)

## If this PR is _not_ a new module
 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` has been updated
 - [ ] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change

### CODE REVIEW

**Comment by ewels** [comment]
This is maybe a little late to be asking this, but is there a reason that we can’t just take the value for mean coverage from the Qualimap output?


https://github.com/ewels/MultiQC_TestData/blob/310327cf2bbaa28b713f9b3e2e7c5b60b2e0ae74/data/modules/qualimap/bam_qc/ERR089819.qc/genome_results.txt#L61

**Comment by apeltzer** [comment]
Sure, can do that - makes probably sense to do that. The median isn't there so its fine to compute that "by hand".

**Comment by apeltzer** [comment]
done and adjusted 👍

**Comment by ewels** [comment]
Tested and works. Thanks again @apeltzer!

**Comment by CuriusScientist** [comment]
I see that you have fixed and merged the branch.

In order to get the latest version, I followed the following steps

- Downaloded MultiQC from github

- Ran successfully "pip install MultiQC-master.zip"
Successfully built multiqc
Installing collected packages: multiqc
Successfully installed multiqc-1.9.dev0

- multiqc ./
[INFO   ]         multiqc : This is MultiQC v1.9.dev0
[INFO   ]         multiqc : Template    : default
[WARNING]         multiqc : You are running MultiQC with Python 2.7.16
[WARNING]         multiqc : Please upgrade! MultiQC will soon drop support for Python < 3.6
[INFO   ]         multiqc : Searching   : /Users/nitinsharma/Documents/00_Work_Projects/ULP-WGS_Bravo/QualiMap
Searching 801 files..  [####################################]  100%          
[INFO   ]        qualimap : Found 8 BamQC reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete

BUT I was not able to get mean coverage
Screenshot 2020-04-30 at 10 08 00
what am i missing here?

**Pull request merged**
