### PR TITLE
Add Nextclade module

### LINKED ISSUE #1455: Add Nextclade support
**Tool Details**

- Name of tool: `Nextclade`
- Tool homepage: `https://github.com/nextstrain/nextclade`
- Tool description: `Viral genome alignment, clade assignment, mutation calling, and quality checks`
- Data suitable for MultiQC plot(s): `table`
- Most interesting data for General Stats table: `clade`

**Tool output:**

- Log filename pattern: ~~`*.nextclade.*`~~ _[none]_
- File contents: Full example output files can be obtained from [here](https://nf-co.re/viralrecon/results#viralrecon/results-f0171324a60d1759ca7f5d02351372d97d22cc12/platform_illumina/variants/ivar/nextclade/).

Nextclade can output various file formats as listed [here](https://github.com/nf-core/modules/blob/c8168bc3516d6f8c3dc6d47c5142073cee82934e/software/nextclade/main.nf#L26-L30) but adding `csv` support would be a good start.

### PR DESCRIPTION
**Pull request by ErikDanielsson**
Added new `Nextclade` module.  Some of the columns in the `Nextclade` table should probably removed. Will close #1455.

- [x] This comment contains a description of changes (with reason)
- [x] `CHANGELOG.md` has been updated
- [x] There is example tool output for tools in the <https://github.com/ewels/MultiQC_TestData> repository or attached to this PR
- [x] Code is tested and works locally (including with `--lint` flag)
- [x] `docs/README.md` is updated with link to below
- [x] `docs/modulename.md` is created
- [x] Everything that can be represented with a plot instead of a table is a plot
- [x] Report sections have a description and help text (with `self.add_section`)
- [ ] There aren't any huge tables with > 6 columns (explain reasoning if so)
- [x] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
- [x] Module does not do any significant computational work

### CODE REVIEW

**Comment by schorlton** [comment]
@ErikDanielsson / @ewels, thanks for this awesome contribution. Wondering what else is needed to get this merged?

**Comment by ewels** [comment]
I guess it's still in draft state because of this:

> Some of the columns in the Nextclade table should probably removed.

If you're able to have a look at the outputs and provide suggestions for how to tailor them (what is most useful for a Nextclade user) that would be really helpful!

More generally, I need to finish my summer holiday and then spend a serious amount of time giving MultiQC some love. My plan is to do a release soon (I had intended to do it before I went on holiday), followed up by merging as many PRs / resolving issues as possible with a follow-up release a few weeks later. This one would likely fall into that second release, unless it's a clear cut merge.

Phil

**Comment by jchorl** [comment]
Hi!

I've polished up the branch here - https://github.com/jchorl/MultiQC/commit/ad17bc0efe6d0311807e46b3e9a0d9971754ce17

I hid most of the columns, only exposing the ones of most relevance (brings us to 5 columns, 6 with sample name).

What would be the process of getting this merged? Can we cherry-pick this commit into Erik's branch?

I see there's also merge conflicts that need to be resolved. Would it be easier if I cut a fresh PR?

**Comment by ewels** [comment]
On my phone so a bid fiddly to see exactly what you've done, but assuming you forked and worked from his commits then I think the easiest is to create a new PR. When that is merged this one should close automatically (I think?).

Phil

**Comment by ewels** [comment]
Continued in https://github.com/ewels/MultiQC/pull/1740

**Pull request closed without merging**
