### PR TITLE
Add official Snakemake example

### PR DESCRIPTION
**Pull request by johanneskoester**
Following your tweet, please include this Snakemake example for using MultiQC, with a few additional remarks.

### CODE REVIEW

**Comment by ewels** [comment]
Fantastic - thank you! Only comment is that the default output filename is `multiqc_report.html` instead of just `multiqc.html`...

Love how simple this is with wrappers :)

**Comment by ewels** [comment]
Out of curiosity - do wrappers work with docker / singularity containers too?

**Comment by johanneskoester** [comment]
They do in the sense that you can combine them with a global singularity directive, that is then used as a baseline for each conda stack: https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#combining-conda-package-management-with-containers

Further, it is planned that wrappers also alternatively deliver a container image url where it makes sense. Such that people can also choose to use them with plain singularity mode (`snakemake --use-singularity`).

**Comment by johanneskoester** [comment]
The wrapper renames the output to whatever you like, but I'll nevertheless change the output filename to the default.

**Comment by ewels** [comment]
Great, thanks! What happens to the `multiqc_data` directory output? I guess that can still be used for downstream processing? Sorry for the snakemake novice questions 😄 

Docs look perfect as they are though, thanks!

**Comment by johanneskoester** [comment]
Thank you!

**Comment by ewels** [comment]
I just a couple of very minor formatting and spacing / wording changes in 3d44ad2 that made it easier for me to understand as a complete snakemake newbie :) Hope this is ok!

External docs link: https://multiqc.info/docs/#snakemake

**Pull request merged**
