### PR TITLE
Add snpeff effects

### PR DESCRIPTION
**Pull request by sachalau**
- [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` has been updated
 - [ ] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change

The section `# Counts by effects` was not plotted from snpEff. It is the sections which includes the most data about the effects of any variants (it has more than 20 categories, frameshifs, stop gain, stop less). It includes more info than `Effects by Class` and `Genomic Regions`. I needed this for my project so I would like to include it in the MultiQC, this could be hidden by default if necessary.

Cheers

### CODE REVIEW

**Comment by ewels** [comment]
Hi @sachalau,

I don't really understand why the CI tests are failing for bcl2fastq here, could you please merge in the upstream changes to this branch please? I think that should fix it..

Phil

**Comment by sachalau** [comment]
Hello @ewels ! Could I get a merge on this before the next release please ?
Thanks !

**Comment by ewels** [comment]
Yes - I'm away on paternity leave currently so all MultiQC work is essentially on hold I'm afraid. When I'm back after the summer I will get back up to date - merge all PRs and do a release.

Sorry for the delay! 🍼

**Comment by sachalau** [comment]
No problem, thanks for letting me know !

**Comment by ewels** [comment]
Hi @sachalau,

Many thanks for this! It is now merged at last 😀 

Note that I made a few minor changes, mostly to do with string formatting and using markdown text. See https://github.com/ewels/MultiQC/commit/248ee558d28d60650f43e2fb8ef757728a57981b

Phil

**Pull request merged**
