### PR TITLE
Add top 5 classif in kaiju barplot

### PR DESCRIPTION
**Pull request by noirot**
Generate same graph as kraken, add the top 5 taxons in bargraph

## If this PR is _not_ a new module
 - [X] This comment contains a description of changes (with reason)
 - [X] `CHANGELOG.md` has been updated
 - [X] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change

### CODE REVIEW

**Comment by noirot** [comment]
@ewels , did you see my PR? Do I have to do something ?

**Comment by ewels** [comment]
I did! My storm of MultiQC activity has now passed after the release though, and I'm now trying to catch up with the stuff that I put on hold whilst working on MultiQC 😅 (I'm actually on holiday this week). I'll try to merge this in next week 👍

**Comment by noirot** [comment]
Ok , no pb, I wondered if I did my PR correctly. No emergency.

**Comment by ewels** [comment]
Hi @noirot,

Just looking at the code now and it looks like you have some conflicts with the changes that you introduced in https://github.com/ewels/MultiQC/pull/1218

I'll have a look and see if I can figure out how to resolve them myself..

Phil

**Comment by noirot** [comment]
Yes indeed , but I refactor the few lines changed #1218, but I keep the correction ;)

**Comment by ewels** [comment]
Ok - so we should ignore the code from #1218 and just keep what you have here? Because you did the changes on separate branches which don't share git history, GitHub doesn't know which changes to keep.

**Comment by noirot** [comment]
Yes you can keep this PR. And yes has I had started to developped this part while the bug was discovered I worked on another branch , I should have rebase :/.

**Comment by ewels** [comment]
Ok, I fixed the merge conflicts 👍  Two thoughts:

* Would it be better to organise the bar plot tabs Species > Phylum instead?
    * I guess that most people will be interested in Species level, and this will be more consistent with the Kraken module
* In the test data there are 4 samples for _Phylum_, 2 samples for _Class_ etc. The `Li-2020-14538-3` sample doesn't seem to appear at all.
    * Why do the numbers of samples vary?
    * As a user I would expect all samples to be in all bar plots, with the same number of total reads each time. Even if the entire bar is _Unclassified_ (or a new "missing" category of some kind)

Phil

**Comment by noirot** [comment]
Hi,
I'm back, so ok  to organise the bar plot tabs Species > Phylum instead
And for the variation of the samples numbers, I just wanted to be sure the module doesn't crash if the numbers of sample is not the same at each level. But I don't expect the user use this, I can indeed add a missing category.
Celine

**Comment by noirot** [comment]
Hi @ewels ,
I did what you suggest, does it ok for you now ?

**Comment by ewels** [comment]
Great! I've been swamped with hackathons and codefests recently sorry and am focussing on getting a release out for @nf-core at the moment. When I get back from vacation MultiQC will be back at the top of my list though and I will go through all PRs and do a release then.

If you need this merged to `dev` before then let me know and I can try to squeeze in a review tomorrow.

**Comment by noirot** [comment]
Ok thanks, it can wait, no pb ! Have nice hollidays.

**Review by ewels — APPROVED** [review]
Looks brilliant 🙌🏻

**Comment by ewels** [comment]
Thanks for this @noirot and sorry for the long delay in reviewing it. Merging... 🚀

**Pull request merged**
