### PR TITLE
abricate module

### PR DESCRIPTION
**Pull request by Ikkik**
Many thanks to contributing to MultiQC!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things I request on pull requests (PRs).

## If this PR is _not_ a new module
 - [ ] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` has been updated
 - [ ] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change

## If this PR is for a new module
 - [X] There is example tool output for tools in the https://github.com/ewels/MultiQC_TestData repository
 - [X] Code is tested and works locally (including with `--lint` flag)
 - [X] `CHANGELOG.md` is updated
 - [X] `README.md` is updated
 - [x] `docs/README.md` is updated with link to below
 - [x] `docs/modulename.md` is created
 - [x] Everything that can be represented with a plot instead of a table is a plot
 - [x] Report sections have a description and help text (with `self.add_section`)
 - [x] There aren't any huge tables with > 6 columns (explain reasoning if so)
 - [NA] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
 - [x] Module does not do any significant computational work

### CODE REVIEW

**Comment by ewels** [comment]
Hi @Ikkik,

I'm a little confused - you seem to have a commented-out version of the rseqc module here, with no new abricate module code. Did you miss something when committing / pushing code?

Phil

**Comment by ewels** [comment]
x-ref https://github.com/ewels/MultiQC_TestData/pull/129/

**Comment by Ikkik** [comment]
Sorry about that! I didn't realize I forgot to merge the branch in with main.

**Comment by Ikkik** [comment]
After some consideration, this would probably work best in a plug in

**Comment by telatin** [comment]
Hello everyone!
I would be interested in the plugin (yet I never used one so far), is it available somewhere?

**Comment by ewels** [comment]
Yes, also happy to discuss the reasons for why a plugin is best 😄  I just cast my eye over the code in this PR again and I can't see anything obvious which is highly specific to your setup? But maybe I'm missing something..

**Pull request closed without merging**
