### PR TITLE
Add Atropos tool

### PR DESCRIPTION
**Pull request by lpantano**
Hi again! I come back!

bcbio is using now atropos for adapter trimming that is an adaptation from cutadapt, so many things are similar but there are difference. 

Please,  let me know if it's ok to add the tool, and comment the code to suit the code style.

Thanks!

### CODE REVIEW

**Comment by lpantano** [comment]
Probably it will fails :) I think I should add an example to the data repository?

**Comment by lpantano** [comment]
Opps, I didn't see that in issue list:

https://github.com/ewels/MultiQC/issues/447

Is anybody else working on this, if yes, we can join effort.

**Comment by ewels** [comment]
Great stuff, thanks @lpantano! Yes, @jdidion has already written a module for Atropos, but it's separate to the main MultiQC codebase currently and awaiting a PR + merge.

I guess we can compare what you've both done and hopefully make something awesome? 🎉  Any thoughts @jdidion?

Still need some example output from Atropos in [ewels/MultiQC_TestData](https://github.com/ewels/MultiQC_TestData) before I can do anything to help here..

Phil

**Comment by jdidion** [comment]
Hi @lpantano, thanks for the interest in the Atropos module! Yes, it's been on my todo for a long time to submit as a PR to MultiQC. I needed to finish the paper first (that's finally accepted at PeerJ) and now I'm on parental leave (don't get much work done with a newborn). If you would like to add anything to my module, I'm happy to make you a collaborator on that project. I plan to focus on this as soon as I get back to work.

**Comment by ewels** [comment]
Cool! I had a few ideas for changes after looking at your [example report](https://rawgit.com/jdidion/atropos-multiqc/master/example/multiqc_report.html) actually. In short I think I'd personally collapse all of the repetitive plots by using multiple datasets for each plot type (see [docs](http://multiqc.info/docs/#switching-datasets-1) - for an example see the [cutadapt plot](http://multiqc.info/examples/rna-seq/multiqc_report.html#cutadapt) for `Counts` and `Obs/Exp`). This would make the report a lot shorter and mean that the module only creates a single report section instead of three. There could be datasets for pre- and post-trimming datasets in this way, and R1 and R2 (or possibly just plot all R1 / R2 on the same plot). Do you think that makes sense?

Let me know if I can help with the merge into the main repo. I'd be happy to do it myself, but I don't want you to lose GitHub credit 😉  If you want to just do a very basic addition of the files in a PR I can wrap up the compatibility and testing myself though (plus the above changes if you agree).

Phil

**Comment by ewels** [comment]
ps. Congrats on the publication! :)

**Comment by lpantano** [comment]
I think those ideas are great. @jdidion repo is much better, and adding that change to merge plots will make it much better. Personally, I'd like to have this as soon as possible because we already moved to atropos :) I don't know if the best strategy is to fork the original repo, and then merge it after all changes, or do the pull request and @ewels can fix it before merging it...I think making a simple PR and then modifying is the best if @ewels has time :) but @jdidion should decide how to work on this! 

thanks!

**Comment by ekopylova** [comment]
Thanks for your work @lpantano and @jdidion! Would love to see this tool merged in MultiQC. Is there something I can help with to move that forward?

**Comment by ewels** [comment]
Hi @ekopylova,

We're just waiting for @jdidion to reply at the moment - I think all of the code is written and basically ready to go, we just need his input for how he would like us to proceed. He mentioned above that he will get to this when he's back to work from paternal leave, so it could be while though..

Phil

**Comment by ekopylova** [comment]
Thanks @ewels , that makes sense. @jdidion congrats!

**Comment by ewels** [comment]
In the mean time, I think you should be able to use @jdidion's code by installing his plugin in addition to MultiQC:

```
pip install multiqc
pip install git+https://github.com/jdidion/atropos-multiqc.git
```

Then stuff _should_ just magically work.. :)

**Comment by jdidion** [comment]
Sorry for the delay on this. I will get on it ASAP.

**Comment by ewels** [comment]
Hi @lpantano,

I'll close this PR now that #614 is open and under review. Thanks again for your work!

Phil

**Pull request closed without merging**
