### PR TITLE
Xenome: show percentages by default, add table and sections

### PR DESCRIPTION
**Pull request by vladsavelyev**
Few adjustments to the Xenome module based on the feedback from @tamuanand (including https://github.com/ewels/MultiQC/pull/1860#issuecomment-1797005564)

1. In the table columns and plots, showing the percentages by default:

Screenshot 2023-11-07 at 18 31 54

2. Added a summary table in addition to the general stats columns. Added there hidden columns for read counts.

3. Properly added section wrappers to the plots to make sure they appear in the contents panel.

4. Additionally, making sure that the color scales for species in the table match the colors in the bar plot.

### CODE REVIEW

**Comment by tamuanand** [comment]
Thanks a ton @vladsavelyev for working on this.

**Review by ewels — APPROVED** [review]
LGTM to merge after the suggested docs additions are made 👍🏻

**Comment by tamuanand** [comment]
@vladsavelyev is this available in a dev version that I can try out after installing with pip like this?

```
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

**Comment by vladsavelyev** [comment]
@tamuanand, after the PR is merged - yes. Before that, you would need to specify the branch name as well:

```sh
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git@xenome
```

If you do it often though, it's convenient to keep a clone of the repo locally:

```sh
git clone https://github.com/ewels/MultiQC.git
```

And run `pip install -e MultiQC`, so the `multiqc` installation uses the exact locally cloned code base in the `MultiQC` folder.

You can optionally check out a specific branch:

```sh
cd MultiQC
git checkout xenome
```

And you installation will switch into it automatically without need to do `pip install` again.

**Pull request merged**
