### PR TITLE
Picard basecalling metrics

### PR DESCRIPTION
**Pull request by matthdsm**
This PR add 4 new metrics wrt base calling using picard
- CollectIlluminaBasecallingMetrics 
- CollectIlluminaLaneMetrics
- ExtractIlluminaBarcodes
- MarkIlluminaAdapters

PR Checklist:

 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` has been updated
 - [x] There is example tool output for tools in the https://github.com/ewels/MultiQC_TestData repository or attached to this PR
 - [x] Code is tested and works locally (including with `--lint` flag)
 - [x] `docs/README.md` is updated with link to below
 - [x] `docs/modulename.md` is created
 - [x] Everything that can be represented with a plot instead of a table is a plot
 - [ ] Report sections have a description and help text (with `self.add_section`)
 - [ ] There aren't any huge tables with > 6 columns (explain reasoning if so)
 - [x] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
 - [x] Module does not do any significant computational work

### CODE REVIEW

**Comment by matthdsm** [comment]
Hi Phil, (hope you don't mind calling me calling you Phil)

I'm unsure as to what would be the best way to format the data from [CollectIlluminaBasecallingMetrics](https://github.com/matthdsm/MultiQC_TestData/tree/picard_basecalling/data/modules/picard/CollectIlluminaBasecallingMetrics). Would you mind giving some input on how you'd envsion it formatted and displayed?

Thanks
Matthias

**Comment by matthdsm** [comment]
Hi Phil,

Is there anything we can do to speed up a merge?

Thanks
M

**Comment by ewels** [comment]
Hi @matthdsm,

I'm working through issues and pull-requests in age order when I get time. I'll do my best to get here as soon as I can.

The best thing that you can do is make sure that this PR is totally ready to go when I do make it here, so that I can review and merge with minimal work / back and forth. Getting the automated tests to pass would be a good start! Also resolving the merge conflicts that have appeared (will likely be more in the future as I merge more PRs - typically they are just the changelog and easy to fix though).

If it's all green ticks when I get here then that's a good starting point 😄 

Phil

**Comment by ewels** [comment]
Tip: Try running MultiQC with the `--lint` flag: https://multiqc.info/docs/#linting-1

Looks like you have lots of anchors / HTML ID tags that are not unique. Docs for report sections: https://multiqc.info/docs/#step-5-create-report-sections (could also be plot IDs or table headers).

Phil

**Comment by ewels** [comment]
Ok, I managed to fix the (quite nasty) merge conflicts and sort out the failing CI tests. It's late now but I will try to go through the new code and report outputs soon.

Phil

**Comment by matthdsm** [comment]
Hi Phil,

SO sorry to have dumped this mess on you. It's been on my to do forever but I haven't gotten around to it.
Thanks for al the work you put in.

Matthias

**Comment by ewels** [comment]
No worries - I'm feeling bad for the merge conflicts on every PR that come from my introduction of the code formatters and I'm getting pretty used to resolving them now so doesn't take me long 😅 

Not sure when I'm going to have time to come back to this so likely not going to make this release sorry. Will to get to it and release again ASAP though.

**Comment by ewels** [comment]
Looking good - thank you @matthdsm ! Sorry again for the long wait.

I have pushed a few minor changes: some table config stuff, bulking out the docs a little and adding links to the Picard docs and so on. Nothing major though. Please do take a look and check that you agree with everything though 👍🏻 

Thanks!

**Comment by matthdsm** [comment]
Looking good! Thanks for the merge!

M

**Pull request merged**
