### PR TITLE
moved entry point to __main__ in the multiqc module

### PR DESCRIPTION
**Pull request by ewels**
See https://github.com/ewels/MultiQC/issues/1002:

---

> I really enjoy using multiqc and I would like to integrate it into my new tool which is currently under development at https://github.com/CompEpigen/CWLab.
> 
> I would like to use multiqc from within python as a module. However, the main function `multiqc()` is at `scripts/multiqc`. Moreover, the people at our lab would also like to use multiqc on their windows computers. Both could be addressed by moving the content of `scripts/multiqc` to `multiqc/__main__.py` and use the default way of specifying command-line entry point in the `setup.py`.
> 
> I already tried out these mild changes in my fork [master...CompEpigen:master](https://github.com/ewels/MultiQC/compare/master...CompEpigen:master).
> 
> The advantages are:
> 
> * you can use mutliqc from within python as any other module:
> 
> ```
> from multiqc import multiqc
> multiqc("/path/to/dir")
> ```
> 
> * you can invoke multiqc with `python -m` and address a specific python interpreter:
> 
> ```
> python -m multiqc .
> python3 -m multiqc .
> ~/my_env/bin/python -m multqc .
> ```
> 
> * you gain windows compatibility
> 
> The only problem I have so far is that the logger display `__main__` instead of `multiqc`. However, this should be easy to fix.
>

### CODE REVIEW

**Comment by ewels** [comment]
Looking at the diff, it seems that you've copied the main MultiQC scripts file instead of doing a `git mv`? It just shows that you added lots of code 😎

**Comment by KerstenBreuer** [comment]
> Looking at the diff, it seems that you've copied the main MultiQC scripts file instead of doing a `git mv`? It just shows that you added lots of code 😎

Sorry, yes I just copied it (I am using vscode for code tracking with git, this unfortunately doesn't recognize if I move something). Now, I used `git mv` to keep the history for respective code.

**Comment by KerstenBreuer** [comment]
Seems like the code is passing now on Travis. However, for AppVeyor, we need to change the test to just invoke multiqc with `multiqc %APPVEYOR_BUILD_FOLDER%\MultiQC_TestData-master\data --ignore` and not the original script.

**Comment by ewels** [comment]
> Now, I used `git mv` to keep the history for respective code.

Thanks! Though when I view the file on GitHub it looks like the history is gone still: 
image

You may need to revert your initial commits, then do the `git mv` command as a standalone commit or something? I feel like maintaining git history when moving files can be a bit of black magic sometimes... 

> However, for AppVeyor, we need to change the test 

Yes I figured this would be the case.. Code is in [`appveyor.yml`](https://github.com/ewels/MultiQC/blob/master/appveyor.yml). Being able to just use the `multiqc` command directly is a great improvement!

**Comment by ewels** [comment]
> You may need to revert your initial commits

Apologies, _revert_ was the wrong term to use. I think you need to rewrite your git history so that the first commit never happened. `git rebase -i HEAD~8`

**Comment by KerstenBreuer** [comment]
> > You may need to revert your initial commits
> 
> Apologies, _revert_ was the wrong term to use. I think you need to rewrite your git history so that the first commit never happened. `git rebase -i HEAD~8`

No worry. Actually, I am learning a lot right now :D

**Comment by KerstenBreuer** [comment]
I actually think the history is just hidden on github.

When you run:
```
$ git log multiqc/__main__.py | tail -n 100
commit 234edcf59ebc033077aed675d341f30cf4567169
Author: kerstenbreuer <kersten-breuer@outlook.com>
Date:   Wed Aug 14 23:45:31 2019 +0200

    moved command line entry point from `scripts/multiqc` to `multiqc/__main__.py`
```

However, when you instead use:
```$ git log --follow multiqc/__main__.py | tail -n 50

    Renamed 'basic stats' to 'general stats'

commit 4bcc365efd31c0625199b82a95cfde97e102545e
Author: Phil Ewels <phil.ewels@scilifelab.se>
Date:   Tue Aug 11 15:13:47 2015 +0200

    Testing. Added exception + handling for when no samples found.

commit 50cf5d63e139540f9849d9a7f6cdee024a724f92
Author: Phil Ewels <phil.ewels@scilifelab.se>
Date:   Tue Aug 11 14:58:34 2015 +0200

    Added Trim Galore! module. Made the 'Basic Stats' table accessible to all modules.

commit ef22b498bb03b7915455066a22b9af4459a4e8f4
Author: Phil Ewels <phil.ewels@scilifelab.se>
Date:   Mon Aug 10 17:50:17 2015 +0200

    Readme update.

commit ecd57b0e32d0ed3639f1547619e5913d079681d6
Author: Phil Ewels <phil.ewels@scilifelab.se>
Date:   Mon Aug 10 17:35:31 2015 +0200

    Couple of tweaks before home.

commit 94eec0cacf5a240a6b0dee69acc09f1f311c9314
Author: Phil Ewels <phil.ewels@scilifelab.se>
Date:   Mon Aug 10 17:06:03 2015 +0200

    Rewriting the theme to have a proper navigation and page layout.

commit 560589a61ece97e982ed913e3d8040027bf6d16c
Author: Phil Ewels <phil.ewels@scilifelab.se>
Date:   Fri Aug 7 14:31:33 2015 +0200

    New FastQC per-base seq content heatmap plot. Report now full-width.

commit 4a11072b02bf53f17c3a96281bd77d9d9fb6513e
Author: Phil Ewels <phil.ewels@scilifelab.se>
Date:   Wed Aug 5 15:27:22 2015 +0200

    Made modules use directories instead of scripts. Copy module assets. FastQC module now finds and loads reports.

commit 8a665aaf435b0a1cb4382f0eadb095593330ef17
Author: Phil Ewels <phil.ewels@scilifelab.se>
Date:   Wed Aug 5 11:58:55 2015 +0200

    Continuing to build main structure of tool.
```
... you are also getting the oldest commits.
So I would think the history is still there?

**Comment by ewels** [comment]
Sigh - you're right, it's just not shown: https://github.com/isaacs/github/issues/900

**Comment by KerstenBreuer** [comment]
I edited the `appveyor.yml`. Do you know, why the test is not running anymore?

**Comment by ewels** [comment]
No I don't.. I've just manually triggered a re-build for the PR, hopefully that'll fix it.

**Pull request merged**
