### PR TITLE
Test

### PR DESCRIPTION
**Pull request by SherryH1229**
Many thanks to contributing to MultiQC!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things I request on pull requests (PRs).

## If this PR is _not_ a new module
 - [ ] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` has been updated
 - [ ] (optional but recommended): https://github.com/ewels/MultiQC_TestData contains test data for this change

## If this PR is for a new module
 - [ ] There is example tool output for tools in the https://github.com/ewels/MultiQC_TestData repository
 - [ ] Code is tested and works locally (including with `--lint` flag)
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated
 - [ ] `docs/README.md` is updated with link to below
 - [ ] `docs/modulename.md` is created
 - [ ] Everything that can be represented with a plot instead of a table is a plot
 - [ ] Report sections have a description and help text (with `self.add_section`)
 - [ ] There aren't any huge tables with > 6 columns (explain reasoning if so)
 - [ ] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
 - [ ] Module does not do any significant computational work

### CODE REVIEW

**Comment by SherryH1229** [comment]
Sorry for mis-pulling. I just want to pull to my forked branch.

**Comment by ewels** [comment]
No problem, and thanks for the explanation :)

Note that if you have an internal-only module, then you can write it as a [plugin](http://multiqc.info/docs/#multiqc-plugins) (see [example](

**Comment by ewels** [comment]
No problem, and thanks for the explanation :)

Note that if you have an internal-only module, then you can write it as a [plugin](http://multiqc.info/docs/#multiqc-plugins) (see [example](https://github.com/MultiQC/example-plugin)). Then the code and installation is separate from the main MultiQC code base and you don’t need to worry about pulling updates.

If this is for a tool that is open then it’s better to keep it as it is and add it back for everyone at some point in the future though.. :)

**Comment by ewels** [comment]
(Oops, clumsy fingers on my mobile sorry)

**Pull request closed without merging**
