### PR TITLE
Fix AdapterRemoval v2 

### PR DESCRIPTION
**Pull request by apeltzer**
This builds on top of work by @alexhbnr and follows the discussion in #1005 to get things fixed. I'll try to get to the points we discussed there tomorrow then ideally to get this hopefully in a useful state. Will get back to what Mikkel said in the PR and help him getting a JSON output for his rewrite but having a (backwards) compatible solution is I think a good idea - can then later have a switch in this module to read either the current log output or the JSON and prefer the JSON over this parser ...? 

@jfy133 to let you know about it :-)

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` has been updated

- [x] There is example tool output for tools in the https://github.com/ewels/MultiQC_TestData repository or attached to this PR
- [ ] Code is tested and works locally (including with `--lint` flag)
- [ ] `docs/README.md` is updated with link to below
- [ ] `docs/modulename.md` is created
- [ ] Everything that can be represented with a plot instead of a table is a plot
- [ ] Report sections have a description and help text (with `self.add_section`)
- [ ] There aren't any huge tables with > 6 columns (explain reasoning if so)
- [ ] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
- [ ] Module does not do any significant computational work

### CODE REVIEW

**Comment by ewels** [comment]
Please see https://github.com/ewels/MultiQC/blob/master/CHANGELOG.md#major-change-code-linting for failing tests 😄

**Comment by fgvieira** [comment]
Since there is an open PR to fix `AdapterRemoval`, I though I'd bring this here.

In the `Adapter Removal` module there is a section for `Length Distribution Paired End Collapsed`, but it then allows o select for singletons, discarded, etc...

image

If it is PE, why allow for reads that are not PE? Or is it the title that is wrong?

**Comment by jfy133** [comment]
Hi @fgvieira - actually there is a lot of problems with the current implementation, to follow the saga please see here: https://github.com/ewels/MultiQC/issues/1005

If you happen to be able to restrucutre the whole module based on the info in that thread that would be awesome!

**Comment by ewels** [comment]
Solved by https://github.com/ewels/MultiQC/pull/1647

**Pull request closed without merging**
