### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/ewels/MultiQC/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/ewels/MultiQC).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by ewels** [comment]
Thanks @xcorail - looks like a nice tool! I've added an issue to look into it (#868) and will merge your PR once I'm happy.

Phil

**Comment by ewels** [comment]
Thanks! Yes, testing it out over here: https://github.com/nf-core/tools/pull/220 just now and it seems nice 👍

**Comment by xcorail** [comment]
Thanks for the feedback. Don't hesitate to give more feedback, suggestions, and also get support (still for free) on our [forum](https://discuss.lgtm.com/)
Cheers

**Comment by xcorail** [comment]
Hey. I am closing this PR as there hasn't been activity on it for a while. Cheers.

**Pull request closed without merging**
