### PR TITLE
add somalier module

### PR DESCRIPTION
**Pull request by brentp**
Many thanks to contributing to MultiQC!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things I request on pull requests (PRs).

## If this PR is for a new module
 - [ ] There is example tool output for tools in the https://github.com/ewels/MultiQC_TestData repository
 - [X] Code is tested and works locally (including with `--lint` flag)
 - [X] `CHANGELOG.md` is updated
 - [X] `README.md` is updated
 - [X] `docs/README.md` is updated with link to below
 - [X] `docs/modulename.md` is created
 - [X] Everything that can be represented with a plot instead of a table is a plot
 - [X] Report sections have a description and help text (with `self.add_section`)
 - [X] There aren't any huge tables with > 6 columns (explain reasoning if so)
 - [X] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
 - [X] Module does not do any significant computational work

here is an example report on 2504 samples from thousand genomes.
http://home.chpc.utah.edu/~u6000771/multiqc_report.html

### CODE REVIEW

**Comment by ewels** [comment]
Ah, nice! Any chance you could submit a PR with some example somalier output files to https://github.com/ewels/MultiQC_TestData please?

Cheers,

Phil

**Comment by ewels** [comment]
Test failure looks like it was just a download timeout. I've triggered a rebuild.

**Comment by brentp** [comment]
yes, will add test-data. meant to mark this as WIP. would also take feedback on plots.
the somalier output has drop-down boxes to choose X, Y axes: http://home.chpc.utah.edu/~u6000771/somalier/glioma.html

is there a way to do that in multiqc?
I'll get a PR up for example data next week, if not before.

**Comment by ewels** [comment]
> is there a way to do that in multiqc?

Not currently. The closest to this is the scatter plot that you can use for any table:

Oct-25-2019 16-05-41

**Comment by ewels** [comment]
Hi @brentp,

Any progress on this PR?

Cheers,

Phil

**Comment by brentp** [comment]
I think we can close this one; i think another is forthcoming from someone else.

**Comment by ewels** [comment]
ok cool - shame, looked like you had come quite far with this code!

**Pull request closed without merging**
