### PR TITLE
mosdepth: display contig name in coverage per contig plot 

### PR DESCRIPTION
**Pull request by pontushojer**
- [X] This comment contains a description of changes (with reason)
 - [X] `CHANGELOG.md` has been updated

Tooltip in _Coverage per contig_ plot showed x-index which is much less useful than the actual contig name. Y-value formatted as before.

### CODE REVIEW

**Comment by nservant** [comment]
Hi,
I just find a small issue in the Average Coverage per Contig plot in MultiQC with the labels display on hover.
The chromosome name is in 'X', and the mean depth in '%'.
For instance, chr1 at 110X is labelled "0X: 110%"
Just wondering if this is fixed in the pull request too ?
Thanks
Nicolas

**Comment by pontushojer** [comment]
Hi @nservant! I have not seen exact the same labels as you mention for the Average Coverage per Contig plot. For me labels were (using the same example as you): `0: 110X`. With this PR the `0` is replaced for the actual contig-name making the label: `chr1: 110X` in this case.

**Comment by nservant** [comment]
ok. Thanks @pontushojer 
I will test the new version and see how it goes. Thanks

**Comment by ewels** [comment]
Thanks both! Very minor PR so have merged quickly without much testing 👀 

@nservant if you could install the dev version and confirm that this change is also what you're looking for, that would be brilliant. Thanks!

**Pull request merged**
