### PR TITLE
Cellranger module

### PR DESCRIPTION
**Pull request by edg1983**
Hello MultiQC team,
I've created a new module to integrate cellranger QC metrics from VDJ or count analysis into MultiQC reports

- [x] `CHANGELOG.md` has been updated
- [X] There is example tool output for tools in the <https://github.com/ewels/MultiQC_TestData> repository or attached to this PR. I've attached 2 HTML example reports in the ZIP archive.
- [X] Code is tested and works locally (including with `--lint` flag)
    - Actually, the report is generated correclty, but using `--lint` I get these warnings
    ```
    LINT: >cellranger/vdj.py< HTML ID was a duplicate (reads-1) ## {'namespace': 'Cellranger VDJ'}
    LINT: >cellranger/vdj.py< HTML ID was a duplicate (valid_bc-1) ## {'namespace': 'Cellranger VDJ'}
    LINT: >cellranger/vdj.py< HTML ID was a duplicate (Q30_bc-1) ## {'namespace': 'Cellranger VDJ'}
    LINT: >cellranger/vdj.py< HTML ID was a duplicate (Q30_UMI-1) ## {'namespace': 'Cellranger VDJ'}
    LINT: >cellranger/vdj.py< HTML ID was a duplicate (estimated_cells-1) ## {'namespace': 'Cellranger VDJ'}
    LINT: >cellranger/vdj.py< HTML ID was a duplicate (avg_reads_cell-1) ## {'namespace': 'Cellranger VDJ'}
    LINT: >cellranger/vdj.py< HTML ID was a duplicate (reads_in_cells-1) ## {'namespace': 'Cellranger VDJ'}
    ```
- [X] `docs/README.md` is updated with link to below
- [X] `docs/modulename.md` is created
- [X] Everything that can be represented with a plot instead of a table is a plot
- [X] Report sections have a description and help text (with `self.add_section`)
- [X] There aren't any huge tables with > 6 columns (explain reasoning if so)
    - I've tried to keep visible columns to the minimum and generally tables have now 6-9 cols. The ones that are visible are those considered of main interest after discussion with colleagues routinely working with this kind of data.
- [ ] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
- [X] Module does not do any significant computational work

[example_data.zip](https://github.com/ewels/MultiQC/files/8737021/example_data.zip)

### CODE REVIEW

**Comment by ewels** [comment]
Oh nice! People have been asking for a cellranger MultiQC module for ages! 😅 

Linting - means that there's probably a section and a plot with the same `id` / `anchor` or something.

**Comment by edg1983** [comment]
I've fixed the problem with redundant anchor names. Now execution using `--lint` return no errors!

**Comment by berguner** [comment]
Thanks for the module @edg1983 !

I had to change the search pattern `cellranger/count_html` with `contents: '"command": "Cell Ranger", "subcommand": "count"'` to get it working. I am using `cellranger-6.1.1`.

**Comment by edg1983** [comment]
Thanks for reporting this. Actually I've tested it with cellranger count/vdj v6.1.2 and 7.0.0, probably they changed the HTML report slightly compared to v6.1.1. I hope the parsing schema remain valid though and the report get generated correctly also from v.6.1.1 summaries

**Comment by chris-rands** [comment]
@edg1983 This looks great, thanks! Is it ready for testing or is there something in particular blocking the merge (other than the conflicts)? Do you have an example multiqc report that you could share that was generated with the test data?

**Comment by edg1983** [comment]
Hi. The module works fine, but I've made a few recent changes to make the file search pattern compatible also with older versions of CellRanger v6, and these generated merging conflicts. I've attached an example report here.
[multiqc_report_cellranger.html.zip](https://github.com/ewels/MultiQC/files/10086650/multiqc_report_cellranger.html.zip)

**Comment by chris-rands** [comment]
@edg1983 Thank you- I tested the branch and it works great! Minor suggestion: update `fn: "*.html"` to `fn: "*web_summary.html"` in multiqc/utils/search_patterns.yaml to prevent issues with other .html files

**Comment by ewels** [comment]
Hi all,

I tried to resolve the merge conflicts and start fixing up some things to get this PR merged, but I didn't have write access to push to this branch and PR directly (probably as it's coming from an organisation and not a user). Instead, I've moved to a separate branch where I will continue working, here https://github.com/ewels/MultiQC/pull/1821

Let's continue the discussion there 👍🏻

**Pull request merged**
