### PR TITLE
adapt log formatter to log level

### PR DESCRIPTION
**Pull request by robinandeer**
This is my suggestion for how to handle logging at different levels
I couldn't help but tweaking the order in the formatter :stuck_out_tongue: 

Normal logging:

```bash
$ multiqc tests/data
multiqc                   [INFO   ]  Using template default
multiqc                   [INFO   ]  Using title None for report
multiqc                   [INFO   ]  Checking files in tests/data
multiqc                   [INFO   ]  Using output dir /Users/robinandeer/projects/work/MultiQC/multiqc_report
multiqc                   [INFO   ]  Analysing modules qualimap, featureCounts, picard, bismark, star, tophat, bowtie2, bowtie1, cutadapt, fastq_screen, fastqc
multiqc                   [INFO   ]  Saving to /Users/robinandeer/projects/work/MultiQC/multiqc_report
qualimap_module           [INFO   ]  Found 1 reports
feature_counts_module     [INFO   ]  Found 2 reports
picard_module             [INFO   ]  Found 4 reports
bismark_module            [INFO   ]  Found 1 reports
star_module               [INFO   ]  Found 2 reports
tophat_module             [INFO   ]  Found 2 reports
bowtie_module             [INFO   ]  Found 2 reports
bowtie_module             [INFO   ]  Found 2 reports
fastq_screen_module       [INFO   ]  Found 2 reports
multiqc                   [INFO   ]  MultiQC complete
```

... and using `debug`

```bash
$ multiqc tests/data -vvv -f
[2015-09-28 14:23:31,373] multiqc.utils.check_modules                        [DEBUG  ]  Adding modules in sorted order to sorted_modules
[2015-09-28 14:23:31,373] multiqc                                            [INFO   ]  Using template default
[2015-09-28 14:23:31,373] multiqc                                            [INFO   ]  Using title None for report
[2015-09-28 14:23:31,373] multiqc                                            [INFO   ]  Checking files in tests/data
[2015-09-28 14:23:31,373] multiqc                                            [INFO   ]  Using output dir /Users/robinandeer/projects/work/MultiQC/multiqc_report
[2015-09-28 14:23:31,373] multiqc                                            [INFO   ]  Analysing modules qualimap, featureCounts, picard, bismark, star, tophat, bowtie2, bowtie1, cutadapt, fastq_screen, fastqc
[2015-09-28 14:23:31,374] multiqc                                            [WARNING]  Deleting /Users/robinandeer/projects/work/MultiQC/multiqc_report because -f was specified.
[2015-09-28 14:23:31,377] multiqc                                            [INFO   ]  Saving to /Users/robinandeer/projects/work/MultiQC/multiqc_report
[2015-09-28 14:23:31,395] multiqc.modules.qualimap.qualimap_module           [INFO   ]  Found 1 reports
[2015-09-28 14:23:31,418] multiqc.modules.featureCounts.feature_counts_module [INFO   ]  Found 2 reports
[2015-09-28 14:23:31,438] multiqc.modules.picard.picard_module               [INFO   ]  Found 4 reports
[2015-09-28 14:23:31,450] multiqc.modules.bismark.bismark_module             [INFO   ]  Found 1 reports
[2015-09-28 14:23:31,457] multiqc.modules.star.star_module                   [INFO   ]  Found 2 reports
[2015-09-28 14:23:31,465] multiqc.modules.tophat.tophat_module               [INFO   ]  Found 2 reports
[2015-09-28 14:23:31,481] multiqc.modules.bowtie2.bowtie_module              [INFO   ]  Found 2 reports
[2015-09-28 14:23:31,497] multiqc.modules.bowtie1.bowtie_module              [INFO   ]  Found 2 reports
[2015-09-28 14:23:31,521] multiqc.modules.fastq_screen.fastq_screen_module   [INFO   ]  Found 2 reports
[2015-09-28 14:23:31,527] multiqc.modules.fastqc.fastqc_module               [DEBUG  ]  Could not find any reports in ('tests/data',)
[2015-09-28 14:23:31,730] multiqc                                            [INFO   ]  MultiQC complete
```

### CODE REVIEW

**Comment by ewels** [comment]
Hah, back to how it [used to be](https://travis-ci.org/ewels/MultiQC/jobs/81022455) :wink: _(except better)_

Two things - I think that the `Analysing modules` message should be `debug` level instead of `info` as it's long and basically never changes. And I think the `title` message should be supressed if it's `None` (as a title of `None` is not used). But I'll do these two tweaks myself as I can probably do them in the time it takes you to read this message..

Nice, thanks!

**Comment by ewels** [comment]
ps. Did you make these paths absolute / `os.realpath` or something? Or did you just supply those super long paths?

**Comment by ewels** [comment]
```python
config.output_dir = os.path.realpath(output_dir)
config.template_fn = os.path.join(output_dir, 'multiqc_report.html')
```
I guess @moonso must have done.. Doesn't matter I guess.

**Comment by robinandeer** [comment]
exactly, not me :)

**Comment by moonso** [comment]
Nice!

**Pull request merged**
