### PR TITLE
Update gene_body_coverage.py

### PR DESCRIPTION
**Pull request by TNalpat**
Using a normalized coverage to make genebody coverage plot ( similar to the method used by RSeQC).

Uses the formula `norm_cov = ( cov - min(cov ) / ( max(cov) - min(cov) )` to compute normalized coverage.

- [x] This comment contains a description of changes (with reason)
- [x] `CHANGELOG.md` has been updated

### CODE REVIEW

**Comment by ewels** [comment]
Great stuff, thanks! If you could add a code comment pointing to the source in the RSeQC code where the same calculation is done, that would be helpful for future maintainers.

Please also add a description of the change to the changelog 👍🏻

**Comment by TNalpat** [comment]
Thank you! I have added necessary code comments. Also adeed a brief description of the change to changelog.

**Comment by ewels** [comment]
> If you could add a code comment pointing to the source in the RSeQC code where the same calculation is done

I more meant a URL to the RSeQC source code where they do this, not just an explanation of what the function is doing 😅  But it's fine, this is clear enough, thanks 👍🏻

**Comment by ewels** [comment]
Also there's no changelog entry yet?

**Comment by TNalpat** [comment]
> > If you could add a code comment pointing to the source in the RSeQC code where the same calculation is done
> 
> I more meant a URL to the RSeQC source code where they do this, not just an explanation of what the function is doing sweat_smile But it's fine, this is clear enough, thanks 👍🏻

:innocent: really sorry for this, I am still getting used with github. Do you mean this https://rseqc.sourceforge.net/#genebody-coverage-py ?

**Comment by TNalpat** [comment]
> Also there's no changelog entry yet?

Looks like I really need some expert help here. I have updated the changelog here : https://github.com/TNalpat/MultiQC/blob/TNalpat-patch-1/CHANGELOG.md

**Comment by TNalpat** [comment]
Sorry , there was a "." in my changelog entry which made the some checks failed. I fixed the changelog, I hope everyhing is good now.

**Comment by ewels** [comment]
Looks good! Sorry, I updated the checks just a day or two ago, so lacking documentation currently. It's so that you can run them locally before pushing using [pre-commit](https://pre-commit.com/). (Run `pre-commit install` and then the tests will run every time you do `git commit` and fix stuff like this automatically for you).

**Comment by ewels** [comment]
> 😇 really sorry for this, I am still getting used with github. Do you mean this https://rseqc.sourceforge.net/#genebody-coverage-py ?

Nothing fancy - you just said that in RSeQC the calculation was done this way. I was curious where you had seen this. If it was in the code I was thinking you could link to the relevant code. I'd forgotten that RSeQC is hosted on SourceForge though 🤦🏻  so not easy. With GitHub you can very easily link to a specific line in a specific project with a permalink.

Don't worry about it anyway 👍🏻

**Pull request merged**
