### PR TITLE
Add BBMap

### PR DESCRIPTION
**Pull request by epruesse**
Adding for convenience of viewing progress and commenting. It's not working yet.

### CODE REVIEW

**Comment by ewels** [comment]
Hi both - any progress with this PR? I'm hoping to get a MultiQC release out in the coming days so trying to tidy up loose ends.

No problem if that's not feasible at this time - happy to leave the PR running, just wanted to let you know that a release was on the cards as they don't come up all that often :)

Cheers,

Phil

**Comment by ewels** [comment]
ps. Let me know if you'd like me to help with this at all!

**Comment by epruesse** [comment]
I'm traveling for the next two weeks, so unlikely I'll get much done. Once I'm back I'll hopefully find some time.

**Comment by ewels** [comment]
Sounds good - enjoy @epruesse!

**Comment by ewels** [comment]
Now merged in the other PR, so closing this.

**Pull request closed without merging**
